#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
DESKTOP_ROOT = REPO_ROOT / "apps/desktop"
I18N_INPUT_DIR = DESKTOP_ROOT / "lib/src/i18n"
MACOS_RUNNER_DIR = DESKTOP_ROOT / "macos/Runner"
SWIFT_OUTPUT_PATH = MACOS_RUNNER_DIR / "Shared/I18n/LocaleKeys.swift"
SWIFT_KEYWORDS = {
    "associatedtype",
    "break",
    "case",
    "catch",
    "class",
    "continue",
    "default",
    "defer",
    "deinit",
    "do",
    "else",
    "enum",
    "extension",
    "fallthrough",
    "false",
    "fileprivate",
    "for",
    "func",
    "guard",
    "if",
    "import",
    "in",
    "init",
    "inout",
    "internal",
    "is",
    "let",
    "nil",
    "open",
    "operator",
    "private",
    "protocol",
    "public",
    "repeat",
    "rethrows",
    "return",
    "self",
    "static",
    "struct",
    "subscript",
    "super",
    "switch",
    "throw",
    "throws",
    "true",
    "try",
    "typealias",
    "var",
    "where",
    "while",
}


def main() -> int:
    if not I18N_INPUT_DIR.exists():
        print(f"Missing Flutter i18n directory: {I18N_INPUT_DIR}", file=sys.stderr)
        return 1

    input_paths = sorted(I18N_INPUT_DIR.glob("*.i18n.json"))
    if not input_paths:
        print(f"No Flutter i18n JSON files found in: {I18N_INPUT_DIR}", file=sys.stderr)
        return 1

    print("Generating macOS Localizable.strings...", flush=True)
    all_keys: set[str] = set()
    for input_path in input_paths:
        locale = input_path.name.removesuffix(".i18n.json")
        output_dir = MACOS_RUNNER_DIR / f"{locale}.lproj"
        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / "Localizable.strings"
        messages = flatten_messages(json.loads(input_path.read_text()))
        all_keys.update(messages)
        output_path.write_text(render_strings_file(messages))

    print("Generating macOS i18n key constants...", flush=True)
    SWIFT_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    SWIFT_OUTPUT_PATH.write_text(render_swift_keys_file(sorted(all_keys)))

    return 0


def flatten_messages(value: Any, prefix: str = "") -> dict[str, str]:
    if isinstance(value, str):
        return {prefix: value}
    if not isinstance(value, dict):
        return {}

    messages: dict[str, str] = {}
    for key, child in value.items():
        child_prefix = key if not prefix else f"{prefix}.{key}"
        messages.update(flatten_messages(child, child_prefix))
    return messages


def render_strings_file(messages: dict[str, str]) -> str:
    lines = [
        "/* This file is automatically generated. Do not edit by hand. */",
        "",
    ]
    for key in sorted(messages):
        lines.append(f'"{escape_string(key)}" = "{escape_string(messages[key])}";')
    lines.append("")
    return "\n".join(lines)


def render_swift_keys_file(keys: list[str]) -> str:
    tree = build_key_tree(keys)
    lines = [
        "// This file is automatically generated. Do not edit by hand.",
        "",
        "import Foundation",
        "",
        "struct LocaleKey: RawRepresentable {",
        "  let rawValue: String",
        "",
        "  init(rawValue: String) {",
        "    self.rawValue = rawValue",
        "  }",
        "",
        "  init(_ rawValue: String) {",
        "    self.rawValue = rawValue",
        "  }",
        "}",
        "",
        "extension LocaleKey {",
        "  func tr() -> String {",
        "    AppLocale.shared.localizedString(rawValue)",
        "  }",
        "",
        "  func tr(_ args: CVarArg...) -> String {",
        "    var template = tr()",
        '    for _ in args { template = template.replacingOccurrences(of: "{}", with: "%@", options: [], range: template.range(of: "{}")) }',
        "    return String(format: template, locale: Locale.current, arguments: args)",
        "  }",
        "}",
        "",
        "enum LocaleKeys {",
    ]
    render_swift_key_tree(lines, tree, indent=2, key_prefix=[])
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def build_key_tree(keys: list[str]) -> dict[str, Any]:
    tree: dict[str, Any] = {}
    for key in keys:
        current = tree
        parts = key.split(".")
        for part in parts[:-1]:
            current = current.setdefault(part, {})
        current[parts[-1]] = key
    return tree


def render_swift_key_tree(
    lines: list[str],
    tree: dict[str, Any],
    *,
    indent: int,
    key_prefix: list[str],
) -> None:
    padding = " " * indent
    for raw_name in sorted(tree):
        value = tree[raw_name]
        swift_name = swift_identifier(raw_name)
        if isinstance(value, dict):
            lines.append(f"{padding}enum {swift_name} {{")
            render_swift_key_tree(
                lines,
                value,
                indent=indent + 2,
                key_prefix=[*key_prefix, raw_name],
            )
            lines.append(f"{padding}}}")
        else:
            lines.append(f'{padding}static let {swift_name} = LocaleKey("{escape_swift_string(value)}")')


def swift_identifier(name: str) -> str:
    parts = [part for part in name.replace("-", "_").split("_") if part]
    if not parts:
        identifier = "_"
    else:
        identifier = parts[0] + "".join(part[:1].upper() + part[1:] for part in parts[1:])

    identifier = "".join(char if char.isalnum() or char == "_" else "_" for char in identifier)
    if identifier[:1].isdigit():
        identifier = f"_{identifier}"
    if identifier in SWIFT_KEYWORDS:
        identifier = f"`{identifier}`"
    return identifier


def escape_swift_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def escape_string(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
    )


if __name__ == "__main__":
    raise SystemExit(main())
