#!/usr/bin/env python3
from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path


INPUT_PATH = Path("rust/src/domain/settings.rs")
OUTPUT_PATH = Path("macos/Runner/Features/Settings/Models/Settings.swift")

SECTION_MODELS = [
    "ShortcutSettings",
    "AppearanceSettings",
    "AdvancedSettings",
]


@dataclass(frozen=True)
class FieldDef:
    rust_name: str
    wire_name: str
    swift_name: str
    swift_type: str


@dataclass(frozen=True)
class StructDef:
    name: str
    has_patch: bool
    fields: list[FieldDef]


@dataclass(frozen=True)
class SettingsFieldDef:
    name: str
    type_name: str


def main() -> int:
    if not INPUT_PATH.exists():
        print(f"Missing Rust settings source: {INPUT_PATH}", file=sys.stderr)
        return 1

    source = INPUT_PATH.read_text()
    parsed = parse_structs(source)
    settings_fields = parse_settings_fields(source)
    structs = [parsed[name] for name in SECTION_MODELS if name in parsed]
    missing = sorted(set(SECTION_MODELS) - set(parsed.keys()))
    if missing:
        print(f"Missing expected Rust settings structs: {', '.join(missing)}", file=sys.stderr)
        return 1

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(render_swift(settings_fields, structs))
    return 0


def parse_structs(source: str) -> dict[str, StructDef]:
    structs: dict[str, StructDef] = {}
    pattern = re.compile(r"#\[derive\(([^)]*)\)\](.*?)pub struct (\w+) \{(.*?)\n\}", re.S)

    for match in pattern.finditer(source):
        derives = [part.strip() for part in match.group(1).split(",")]
        name = match.group(3)
        if name not in SECTION_MODELS:
            continue

        structs[name] = StructDef(
            name=name,
            has_patch="Patch" in derives,
            fields=parse_fields(match.group(4)),
        )

    return structs


def parse_settings_fields(source: str) -> list[SettingsFieldDef]:
    match = re.search(r"pub struct Settings \{(.*?)\n\}", source, re.S)
    if not match:
        raise ValueError("Missing Rust Settings struct")

    fields: list[SettingsFieldDef] = []
    for raw_line in match.group(1).splitlines():
        line = raw_line.strip()
        field_match = re.match(r"pub (\w+): ([^,]+),", line)
        if not field_match:
            continue

        field_name = field_match.group(1)
        type_name = field_match.group(2).strip()
        if type_name in SECTION_MODELS:
            fields.append(SettingsFieldDef(name=field_name, type_name=type_name))

    return fields


def parse_fields(body: str) -> list[FieldDef]:
    fields: list[FieldDef] = []
    attrs: list[str] = []

    for raw_line in body.splitlines():
        line = raw_line.strip()
        if not line:
            continue

        if line.startswith("#["):
            attrs.append(line)
            continue

        field_match = re.match(r"pub (\w+): ([^,]+),", line)
        if not field_match:
            attrs.clear()
            continue

        rust_name = field_match.group(1)
        rust_type = field_match.group(2).strip()
        fields.append(
            FieldDef(
                rust_name=rust_name,
                wire_name=serde_rename(attrs) or camel_case(rust_name),
                swift_name=camel_case(rust_name),
                swift_type=swift_type_name(rust_type),
            )
        )
        attrs.clear()

    return fields


def serde_rename(attrs: list[str]) -> str | None:
    for attr in attrs:
        match = re.search(r'rename = "([^"]+)"', attr)
        if match:
            return match.group(1)
    return None


def camel_case(snake_case: str) -> str:
    head, *tail = snake_case.split("_")
    return head + "".join(part[:1].upper() + part[1:] for part in tail)


def swift_type_name(rust_type: str) -> str:
    if rust_type == "String":
        return "String"
    if rust_type == "bool":
        return "Bool"
    raise ValueError(f"Unsupported Rust field type: {rust_type}")


def render_swift(settings_fields: list[SettingsFieldDef], structs: list[StructDef]) -> str:
    lines: list[str] = [
        "// This file is automatically generated. Do not edit by hand.",
        "// Generated by `python3 scripts/generate_settings.py`.",
        "",
        "import Foundation",
        "",
    ]

    lines.extend(render_settings_struct(settings_fields))
    lines.append("")

    for struct in structs:
        lines.extend(render_struct(struct, patch=False))
        lines.append("")
        if struct.has_patch:
            lines.extend(render_struct(struct, patch=True))
            lines.append("")

    return "\n".join(lines)


def render_settings_struct(settings_fields: list[SettingsFieldDef]) -> list[str]:
    lines = ["struct Settings: Codable {"]
    for field in settings_fields:
        lines.append(f"  var {field.name}: {field.type_name}")
    lines.append("}")
    return lines


def render_struct(struct: StructDef, *, patch: bool) -> list[str]:
    name = f"{struct.name}Patch" if patch else struct.name
    lines = [f"struct {name}: Codable {{"]

    for field in struct.fields:
        optional = "?" if patch else ""
        lines.append(f"  var {field.swift_name}: {field.swift_type}{optional}")

    renamed = [field for field in struct.fields if field.swift_name != field.wire_name]
    if renamed:
        lines.append("")
        lines.append("  enum CodingKeys: String, CodingKey {")
        for field in struct.fields:
            if field.swift_name == field.wire_name:
                lines.append(f"    case {field.swift_name}")
            else:
                lines.append(f'    case {field.swift_name} = "{field.wire_name}"')
        lines.append("  }")

    lines.append("}")
    return lines


if __name__ == "__main__":
    raise SystemExit(main())
