/* tslint:disable */
/* eslint-disable */
/**
 * BeyondTranslate API
 * HTTP API for translation and dictionary lookups.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DetectLanguageRequest
 */
export interface DetectLanguageRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof DetectLanguageRequest
     */
    texts: Array<string>;
}

/**
 * Check if a given object implements the DetectLanguageRequest interface.
 */
export function instanceOfDetectLanguageRequest(value: object): value is DetectLanguageRequest {
    if (!('texts' in value) || value['texts'] === undefined) return false;
    return true;
}

export function DetectLanguageRequestFromJSON(json: any): DetectLanguageRequest {
    return DetectLanguageRequestFromJSONTyped(json, false);
}

export function DetectLanguageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetectLanguageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'texts': json['texts'],
    };
}

export function DetectLanguageRequestToJSON(json: any): DetectLanguageRequest {
    return DetectLanguageRequestToJSONTyped(json, false);
}

export function DetectLanguageRequestToJSONTyped(value?: DetectLanguageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'texts': value['texts'],
    };
}

