/* tslint:disable */
/* eslint-disable */
/**
 * BeyondTranslate API
 * HTTP API for translation and dictionary lookups.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TextDetection } from './TextDetection';
import {
    TextDetectionFromJSON,
    TextDetectionFromJSONTyped,
    TextDetectionToJSON,
    TextDetectionToJSONTyped,
} from './TextDetection';

/**
 * 
 * @export
 * @interface DetectLanguageResponse
 */
export interface DetectLanguageResponse {
    /**
     * 
     * @type {Array<TextDetection>}
     * @memberof DetectLanguageResponse
     */
    detections?: Array<TextDetection>;
}

/**
 * Check if a given object implements the DetectLanguageResponse interface.
 */
export function instanceOfDetectLanguageResponse(value: object): value is DetectLanguageResponse {
    return true;
}

export function DetectLanguageResponseFromJSON(json: any): DetectLanguageResponse {
    return DetectLanguageResponseFromJSONTyped(json, false);
}

export function DetectLanguageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetectLanguageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'detections': json['detections'] == null ? undefined : ((json['detections'] as Array<any>).map(TextDetectionFromJSON)),
    };
}

export function DetectLanguageResponseToJSON(json: any): DetectLanguageResponse {
    return DetectLanguageResponseToJSONTyped(json, false);
}

export function DetectLanguageResponseToJSONTyped(value?: DetectLanguageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detections': value['detections'] == null ? undefined : ((value['detections'] as Array<any>).map(TextDetectionToJSON)),
    };
}

