/* tslint:disable */
/* eslint-disable */
/**
 * BeyondTranslate API
 * HTTP API for translation and dictionary lookups.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorBody
 */
export interface ErrorBody {
    /**
     * 
     * @type {string}
     * @memberof ErrorBody
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorBody
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorBody
     */
    provider?: string;
}

/**
 * Check if a given object implements the ErrorBody interface.
 */
export function instanceOfErrorBody(value: object): value is ErrorBody {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ErrorBodyFromJSON(json: any): ErrorBody {
    return ErrorBodyFromJSONTyped(json, false);
}

export function ErrorBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorBody {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
        'provider': json['provider'] == null ? undefined : json['provider'],
    };
}

export function ErrorBodyToJSON(json: any): ErrorBody {
    return ErrorBodyToJSONTyped(json, false);
}

export function ErrorBodyToJSONTyped(value?: ErrorBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'provider': value['provider'],
    };
}

