/* tslint:disable */
/* eslint-disable */
/**
 * BeyondTranslate API
 * HTTP API for translation and dictionary lookups.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorBody } from './ErrorBody';
import {
    ErrorBodyFromJSON,
    ErrorBodyFromJSONTyped,
    ErrorBodyToJSON,
    ErrorBodyToJSONTyped,
} from './ErrorBody';

/**
 * 
 * @export
 * @interface ErrorResponseEnvelope
 */
export interface ErrorResponseEnvelope {
    /**
     * 
     * @type {ErrorResponseEnvelopeSuccessEnum}
     * @memberof ErrorResponseEnvelope
     */
    success: ErrorResponseEnvelopeSuccessEnum;
    /**
     * 
     * @type {ErrorBody}
     * @memberof ErrorResponseEnvelope
     */
    error: ErrorBody;
}


/**
 * @export
 */
export const ErrorResponseEnvelopeSuccessEnum = {
    False: false
} as const;
export type ErrorResponseEnvelopeSuccessEnum = typeof ErrorResponseEnvelopeSuccessEnum[keyof typeof ErrorResponseEnvelopeSuccessEnum];


/**
 * Check if a given object implements the ErrorResponseEnvelope interface.
 */
export function instanceOfErrorResponseEnvelope(value: object): value is ErrorResponseEnvelope {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ErrorResponseEnvelopeFromJSON(json: any): ErrorResponseEnvelope {
    return ErrorResponseEnvelopeFromJSONTyped(json, false);
}

export function ErrorResponseEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'error': ErrorBodyFromJSON(json['error']),
    };
}

export function ErrorResponseEnvelopeToJSON(json: any): ErrorResponseEnvelope {
    return ErrorResponseEnvelopeToJSONTyped(json, false);
}

export function ErrorResponseEnvelopeToJSONTyped(value?: ErrorResponseEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'error': ErrorBodyToJSON(value['error']),
    };
}

