/* tslint:disable */
/* eslint-disable */
/**
 * BeyondTranslate API
 * HTTP API for translation and dictionary lookups.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HealthResponse } from './HealthResponse';
import {
    HealthResponseFromJSON,
    HealthResponseFromJSONTyped,
    HealthResponseToJSON,
    HealthResponseToJSONTyped,
} from './HealthResponse';

/**
 * 
 * @export
 * @interface HealthResponseEnvelope
 */
export interface HealthResponseEnvelope {
    /**
     * 
     * @type {HealthResponseEnvelopeSuccessEnum}
     * @memberof HealthResponseEnvelope
     */
    success: HealthResponseEnvelopeSuccessEnum;
    /**
     * 
     * @type {HealthResponse}
     * @memberof HealthResponseEnvelope
     */
    data: HealthResponse;
}


/**
 * @export
 */
export const HealthResponseEnvelopeSuccessEnum = {
    True: true
} as const;
export type HealthResponseEnvelopeSuccessEnum = typeof HealthResponseEnvelopeSuccessEnum[keyof typeof HealthResponseEnvelopeSuccessEnum];


/**
 * Check if a given object implements the HealthResponseEnvelope interface.
 */
export function instanceOfHealthResponseEnvelope(value: object): value is HealthResponseEnvelope {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function HealthResponseEnvelopeFromJSON(json: any): HealthResponseEnvelope {
    return HealthResponseEnvelopeFromJSONTyped(json, false);
}

export function HealthResponseEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthResponseEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': HealthResponseFromJSON(json['data']),
    };
}

export function HealthResponseEnvelopeToJSON(json: any): HealthResponseEnvelope {
    return HealthResponseEnvelopeToJSONTyped(json, false);
}

export function HealthResponseEnvelopeToJSONTyped(value?: HealthResponseEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': HealthResponseToJSON(value['data']),
    };
}

