/* tslint:disable */
/* eslint-disable */
/**
 * BeyondTranslate API
 * HTTP API for translation and dictionary lookups.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LanguagePair
 */
export interface LanguagePair {
    /**
     * 
     * @type {string}
     * @memberof LanguagePair
     */
    sourceLanguage?: string;
    /**
     * 
     * @type {string}
     * @memberof LanguagePair
     */
    sourceLanguageId?: string;
    /**
     * 
     * @type {string}
     * @memberof LanguagePair
     */
    targetLanguage?: string;
    /**
     * 
     * @type {string}
     * @memberof LanguagePair
     */
    targetLanguageId?: string;
}

/**
 * Check if a given object implements the LanguagePair interface.
 */
export function instanceOfLanguagePair(value: object): value is LanguagePair {
    return true;
}

export function LanguagePairFromJSON(json: any): LanguagePair {
    return LanguagePairFromJSONTyped(json, false);
}

export function LanguagePairFromJSONTyped(json: any, ignoreDiscriminator: boolean): LanguagePair {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceLanguage': json['source_language'] == null ? undefined : json['source_language'],
        'sourceLanguageId': json['source_language_id'] == null ? undefined : json['source_language_id'],
        'targetLanguage': json['target_language'] == null ? undefined : json['target_language'],
        'targetLanguageId': json['target_language_id'] == null ? undefined : json['target_language_id'],
    };
}

export function LanguagePairToJSON(json: any): LanguagePair {
    return LanguagePairToJSONTyped(json, false);
}

export function LanguagePairToJSONTyped(value?: LanguagePair | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source_language': value['sourceLanguage'],
        'source_language_id': value['sourceLanguageId'],
        'target_language': value['targetLanguage'],
        'target_language_id': value['targetLanguageId'],
    };
}

