/* tslint:disable */
/* eslint-disable */
/**
 * BeyondTranslate API
 * HTTP API for translation and dictionary lookups.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LanguagePair } from './LanguagePair';
import {
    LanguagePairFromJSON,
    LanguagePairFromJSONTyped,
    LanguagePairToJSON,
    LanguagePairToJSONTyped,
} from './LanguagePair';

/**
 * 
 * @export
 * @interface LanguagePairListEnvelope
 */
export interface LanguagePairListEnvelope {
    /**
     * 
     * @type {LanguagePairListEnvelopeSuccessEnum}
     * @memberof LanguagePairListEnvelope
     */
    success: LanguagePairListEnvelopeSuccessEnum;
    /**
     * 
     * @type {Array<LanguagePair>}
     * @memberof LanguagePairListEnvelope
     */
    data: Array<LanguagePair>;
}


/**
 * @export
 */
export const LanguagePairListEnvelopeSuccessEnum = {
    True: true
} as const;
export type LanguagePairListEnvelopeSuccessEnum = typeof LanguagePairListEnvelopeSuccessEnum[keyof typeof LanguagePairListEnvelopeSuccessEnum];


/**
 * Check if a given object implements the LanguagePairListEnvelope interface.
 */
export function instanceOfLanguagePairListEnvelope(value: object): value is LanguagePairListEnvelope {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function LanguagePairListEnvelopeFromJSON(json: any): LanguagePairListEnvelope {
    return LanguagePairListEnvelopeFromJSONTyped(json, false);
}

export function LanguagePairListEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LanguagePairListEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ((json['data'] as Array<any>).map(LanguagePairFromJSON)),
    };
}

export function LanguagePairListEnvelopeToJSON(json: any): LanguagePairListEnvelope {
    return LanguagePairListEnvelopeToJSONTyped(json, false);
}

export function LanguagePairListEnvelopeToJSONTyped(value?: LanguagePairListEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ((value['data'] as Array<any>).map(LanguagePairToJSON)),
    };
}

