/* tslint:disable */
/* eslint-disable */
/**
 * BeyondTranslate API
 * HTTP API for translation and dictionary lookups.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LookUpResponse } from './LookUpResponse';
import {
    LookUpResponseFromJSON,
    LookUpResponseFromJSONTyped,
    LookUpResponseToJSON,
    LookUpResponseToJSONTyped,
} from './LookUpResponse';

/**
 * 
 * @export
 * @interface LookUpResponseEnvelope
 */
export interface LookUpResponseEnvelope {
    /**
     * 
     * @type {LookUpResponseEnvelopeSuccessEnum}
     * @memberof LookUpResponseEnvelope
     */
    success: LookUpResponseEnvelopeSuccessEnum;
    /**
     * 
     * @type {LookUpResponse}
     * @memberof LookUpResponseEnvelope
     */
    data: LookUpResponse;
}


/**
 * @export
 */
export const LookUpResponseEnvelopeSuccessEnum = {
    True: true
} as const;
export type LookUpResponseEnvelopeSuccessEnum = typeof LookUpResponseEnvelopeSuccessEnum[keyof typeof LookUpResponseEnvelopeSuccessEnum];


/**
 * Check if a given object implements the LookUpResponseEnvelope interface.
 */
export function instanceOfLookUpResponseEnvelope(value: object): value is LookUpResponseEnvelope {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function LookUpResponseEnvelopeFromJSON(json: any): LookUpResponseEnvelope {
    return LookUpResponseEnvelopeFromJSONTyped(json, false);
}

export function LookUpResponseEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LookUpResponseEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': LookUpResponseFromJSON(json['data']),
    };
}

export function LookUpResponseEnvelopeToJSON(json: any): LookUpResponseEnvelope {
    return LookUpResponseEnvelopeToJSONTyped(json, false);
}

export function LookUpResponseEnvelopeToJSONTyped(value?: LookUpResponseEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': LookUpResponseToJSON(value['data']),
    };
}

