/* tslint:disable */
/* eslint-disable */
/**
 * BeyondTranslate API
 * HTTP API for translation and dictionary lookups.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LookUpRequest
 */
export interface LookUpRequest {
    /**
     * 
     * @type {string}
     * @memberof LookUpRequest
     */
    sourceLanguage: string;
    /**
     * 
     * @type {string}
     * @memberof LookUpRequest
     */
    targetLanguage: string;
    /**
     * 
     * @type {string}
     * @memberof LookUpRequest
     */
    word: string;
}

/**
 * Check if a given object implements the LookUpRequest interface.
 */
export function instanceOfLookUpRequest(value: object): value is LookUpRequest {
    if (!('sourceLanguage' in value) || value['sourceLanguage'] === undefined) return false;
    if (!('targetLanguage' in value) || value['targetLanguage'] === undefined) return false;
    if (!('word' in value) || value['word'] === undefined) return false;
    return true;
}

export function LookUpRequestFromJSON(json: any): LookUpRequest {
    return LookUpRequestFromJSONTyped(json, false);
}

export function LookUpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LookUpRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceLanguage': json['source_language'],
        'targetLanguage': json['target_language'],
        'word': json['word'],
    };
}

export function LookUpRequestToJSON(json: any): LookUpRequest {
    return LookUpRequestToJSONTyped(json, false);
}

export function LookUpRequestToJSONTyped(value?: LookUpRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source_language': value['sourceLanguage'],
        'target_language': value['targetLanguage'],
        'word': value['word'],
    };
}

