/* tslint:disable */
/* eslint-disable */
/**
 * BeyondTranslate API
 * HTTP API for translation and dictionary lookups.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WordDefinition } from './WordDefinition';
import {
    WordDefinitionFromJSON,
    WordDefinitionFromJSONTyped,
    WordDefinitionToJSON,
    WordDefinitionToJSONTyped,
} from './WordDefinition';
import type { WordImage } from './WordImage';
import {
    WordImageFromJSON,
    WordImageFromJSONTyped,
    WordImageToJSON,
    WordImageToJSONTyped,
} from './WordImage';
import type { TextTranslation } from './TextTranslation';
import {
    TextTranslationFromJSON,
    TextTranslationFromJSONTyped,
    TextTranslationToJSON,
    TextTranslationToJSONTyped,
} from './TextTranslation';
import type { WordPronunciation } from './WordPronunciation';
import {
    WordPronunciationFromJSON,
    WordPronunciationFromJSONTyped,
    WordPronunciationToJSON,
    WordPronunciationToJSONTyped,
} from './WordPronunciation';
import type { WordPhrase } from './WordPhrase';
import {
    WordPhraseFromJSON,
    WordPhraseFromJSONTyped,
    WordPhraseToJSON,
    WordPhraseToJSONTyped,
} from './WordPhrase';
import type { WordSentence } from './WordSentence';
import {
    WordSentenceFromJSON,
    WordSentenceFromJSONTyped,
    WordSentenceToJSON,
    WordSentenceToJSONTyped,
} from './WordSentence';
import type { WordTense } from './WordTense';
import {
    WordTenseFromJSON,
    WordTenseFromJSONTyped,
    WordTenseToJSON,
    WordTenseToJSONTyped,
} from './WordTense';
import type { WordTag } from './WordTag';
import {
    WordTagFromJSON,
    WordTagFromJSONTyped,
    WordTagToJSON,
    WordTagToJSONTyped,
} from './WordTag';

/**
 * 
 * @export
 * @interface LookUpResponse
 */
export interface LookUpResponse {
    /**
     * 
     * @type {Array<TextTranslation>}
     * @memberof LookUpResponse
     */
    translations: Array<TextTranslation>;
    /**
     * 
     * @type {string}
     * @memberof LookUpResponse
     */
    word?: string;
    /**
     * 
     * @type {string}
     * @memberof LookUpResponse
     */
    tip?: string;
    /**
     * 
     * @type {Array<WordTag>}
     * @memberof LookUpResponse
     */
    tags?: Array<WordTag>;
    /**
     * 
     * @type {Array<WordDefinition>}
     * @memberof LookUpResponse
     */
    definitions?: Array<WordDefinition>;
    /**
     * 
     * @type {Array<WordPronunciation>}
     * @memberof LookUpResponse
     */
    pronunciations?: Array<WordPronunciation>;
    /**
     * 
     * @type {Array<WordImage>}
     * @memberof LookUpResponse
     */
    images?: Array<WordImage>;
    /**
     * 
     * @type {Array<WordPhrase>}
     * @memberof LookUpResponse
     */
    phrases?: Array<WordPhrase>;
    /**
     * 
     * @type {Array<WordTense>}
     * @memberof LookUpResponse
     */
    tenses?: Array<WordTense>;
    /**
     * 
     * @type {Array<WordSentence>}
     * @memberof LookUpResponse
     */
    sentences?: Array<WordSentence>;
}

/**
 * Check if a given object implements the LookUpResponse interface.
 */
export function instanceOfLookUpResponse(value: object): value is LookUpResponse {
    if (!('translations' in value) || value['translations'] === undefined) return false;
    return true;
}

export function LookUpResponseFromJSON(json: any): LookUpResponse {
    return LookUpResponseFromJSONTyped(json, false);
}

export function LookUpResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LookUpResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'translations': ((json['translations'] as Array<any>).map(TextTranslationFromJSON)),
        'word': json['word'] == null ? undefined : json['word'],
        'tip': json['tip'] == null ? undefined : json['tip'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(WordTagFromJSON)),
        'definitions': json['definitions'] == null ? undefined : ((json['definitions'] as Array<any>).map(WordDefinitionFromJSON)),
        'pronunciations': json['pronunciations'] == null ? undefined : ((json['pronunciations'] as Array<any>).map(WordPronunciationFromJSON)),
        'images': json['images'] == null ? undefined : ((json['images'] as Array<any>).map(WordImageFromJSON)),
        'phrases': json['phrases'] == null ? undefined : ((json['phrases'] as Array<any>).map(WordPhraseFromJSON)),
        'tenses': json['tenses'] == null ? undefined : ((json['tenses'] as Array<any>).map(WordTenseFromJSON)),
        'sentences': json['sentences'] == null ? undefined : ((json['sentences'] as Array<any>).map(WordSentenceFromJSON)),
    };
}

export function LookUpResponseToJSON(json: any): LookUpResponse {
    return LookUpResponseToJSONTyped(json, false);
}

export function LookUpResponseToJSONTyped(value?: LookUpResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'translations': ((value['translations'] as Array<any>).map(TextTranslationToJSON)),
        'word': value['word'],
        'tip': value['tip'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(WordTagToJSON)),
        'definitions': value['definitions'] == null ? undefined : ((value['definitions'] as Array<any>).map(WordDefinitionToJSON)),
        'pronunciations': value['pronunciations'] == null ? undefined : ((value['pronunciations'] as Array<any>).map(WordPronunciationToJSON)),
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(WordImageToJSON)),
        'phrases': value['phrases'] == null ? undefined : ((value['phrases'] as Array<any>).map(WordPhraseToJSON)),
        'tenses': value['tenses'] == null ? undefined : ((value['tenses'] as Array<any>).map(WordTenseToJSON)),
        'sentences': value['sentences'] == null ? undefined : ((value['sentences'] as Array<any>).map(WordSentenceToJSON)),
    };
}

