/* tslint:disable */
/* eslint-disable */
/**
 * BeyondTranslate API
 * HTTP API for translation and dictionary lookups.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TextTranslation
 */
export interface TextTranslation {
    /**
     * 
     * @type {string}
     * @memberof TextTranslation
     */
    detectedSourceLanguage?: string;
    /**
     * 
     * @type {string}
     * @memberof TextTranslation
     */
    text: string;
    /**
     * 
     * @type {string}
     * @memberof TextTranslation
     */
    audioUrl?: string;
}

/**
 * Check if a given object implements the TextTranslation interface.
 */
export function instanceOfTextTranslation(value: object): value is TextTranslation {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function TextTranslationFromJSON(json: any): TextTranslation {
    return TextTranslationFromJSONTyped(json, false);
}

export function TextTranslationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TextTranslation {
    if (json == null) {
        return json;
    }
    return {
        
        'detectedSourceLanguage': json['detected_source_language'] == null ? undefined : json['detected_source_language'],
        'text': json['text'],
        'audioUrl': json['audio_url'] == null ? undefined : json['audio_url'],
    };
}

export function TextTranslationToJSON(json: any): TextTranslation {
    return TextTranslationToJSONTyped(json, false);
}

export function TextTranslationToJSONTyped(value?: TextTranslation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detected_source_language': value['detectedSourceLanguage'],
        'text': value['text'],
        'audio_url': value['audioUrl'],
    };
}

