/* tslint:disable */
/* eslint-disable */
/**
 * BeyondTranslate API
 * HTTP API for translation and dictionary lookups.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TranslateResponse } from './TranslateResponse';
import {
    TranslateResponseFromJSON,
    TranslateResponseFromJSONTyped,
    TranslateResponseToJSON,
    TranslateResponseToJSONTyped,
} from './TranslateResponse';

/**
 * 
 * @export
 * @interface TranslateResponseEnvelope
 */
export interface TranslateResponseEnvelope {
    /**
     * 
     * @type {TranslateResponseEnvelopeSuccessEnum}
     * @memberof TranslateResponseEnvelope
     */
    success: TranslateResponseEnvelopeSuccessEnum;
    /**
     * 
     * @type {TranslateResponse}
     * @memberof TranslateResponseEnvelope
     */
    data: TranslateResponse;
}


/**
 * @export
 */
export const TranslateResponseEnvelopeSuccessEnum = {
    True: true
} as const;
export type TranslateResponseEnvelopeSuccessEnum = typeof TranslateResponseEnvelopeSuccessEnum[keyof typeof TranslateResponseEnvelopeSuccessEnum];


/**
 * Check if a given object implements the TranslateResponseEnvelope interface.
 */
export function instanceOfTranslateResponseEnvelope(value: object): value is TranslateResponseEnvelope {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TranslateResponseEnvelopeFromJSON(json: any): TranslateResponseEnvelope {
    return TranslateResponseEnvelopeFromJSONTyped(json, false);
}

export function TranslateResponseEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranslateResponseEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': TranslateResponseFromJSON(json['data']),
    };
}

export function TranslateResponseEnvelopeToJSON(json: any): TranslateResponseEnvelope {
    return TranslateResponseEnvelopeToJSONTyped(json, false);
}

export function TranslateResponseEnvelopeToJSONTyped(value?: TranslateResponseEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': TranslateResponseToJSON(value['data']),
    };
}

