/* tslint:disable */
/* eslint-disable */
/**
 * BeyondTranslate API
 * HTTP API for translation and dictionary lookups.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TranslateRequest
 */
export interface TranslateRequest {
    /**
     * 
     * @type {string}
     * @memberof TranslateRequest
     */
    sourceLanguage?: string;
    /**
     * 
     * @type {string}
     * @memberof TranslateRequest
     */
    targetLanguage?: string;
    /**
     * 
     * @type {string}
     * @memberof TranslateRequest
     */
    text: string;
}

/**
 * Check if a given object implements the TranslateRequest interface.
 */
export function instanceOfTranslateRequest(value: object): value is TranslateRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function TranslateRequestFromJSON(json: any): TranslateRequest {
    return TranslateRequestFromJSONTyped(json, false);
}

export function TranslateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranslateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceLanguage': json['source_language'] == null ? undefined : json['source_language'],
        'targetLanguage': json['target_language'] == null ? undefined : json['target_language'],
        'text': json['text'],
    };
}

export function TranslateRequestToJSON(json: any): TranslateRequest {
    return TranslateRequestToJSONTyped(json, false);
}

export function TranslateRequestToJSONTyped(value?: TranslateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source_language': value['sourceLanguage'],
        'target_language': value['targetLanguage'],
        'text': value['text'],
    };
}

