/* tslint:disable */
/* eslint-disable */
/**
 * BeyondTranslate API
 * HTTP API for translation and dictionary lookups.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WordTense
 */
export interface WordTense {
    /**
     * 
     * @type {string}
     * @memberof WordTense
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof WordTense
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WordTense
     */
    values?: Array<string>;
}

/**
 * Check if a given object implements the WordTense interface.
 */
export function instanceOfWordTense(value: object): value is WordTense {
    return true;
}

export function WordTenseFromJSON(json: any): WordTense {
    return WordTenseFromJSONTyped(json, false);
}

export function WordTenseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordTense {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'name': json['name'] == null ? undefined : json['name'],
        'values': json['values'] == null ? undefined : json['values'],
    };
}

export function WordTenseToJSON(json: any): WordTense {
    return WordTenseToJSONTyped(json, false);
}

export function WordTenseToJSONTyped(value?: WordTense | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'name': value['name'],
        'values': value['values'],
    };
}

