/* tslint:disable */
/* eslint-disable */
/**
 * BeyondTranslate API
 * HTTP API for translation and dictionary lookups.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WordImage
 */
export interface WordImage {
    /**
     * 
     * @type {string}
     * @memberof WordImage
     */
    url: string;
}

/**
 * Check if a given object implements the WordImage interface.
 */
export function instanceOfWordImage(value: object): value is WordImage {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function WordImageFromJSON(json: any): WordImage {
    return WordImageFromJSONTyped(json, false);
}

export function WordImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordImage {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function WordImageToJSON(json: any): WordImage {
    return WordImageToJSONTyped(json, false);
}

export function WordImageToJSONTyped(value?: WordImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

