/* tslint:disable */
/* eslint-disable */
/**
 * BeyondTranslate API
 * HTTP API for translation and dictionary lookups.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WordSentence
 */
export interface WordSentence {
    /**
     * 
     * @type {string}
     * @memberof WordSentence
     */
    text: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WordSentence
     */
    translations: Array<string>;
}

/**
 * Check if a given object implements the WordSentence interface.
 */
export function instanceOfWordSentence(value: object): value is WordSentence {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('translations' in value) || value['translations'] === undefined) return false;
    return true;
}

export function WordSentenceFromJSON(json: any): WordSentence {
    return WordSentenceFromJSONTyped(json, false);
}

export function WordSentenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordSentence {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'translations': json['translations'],
    };
}

export function WordSentenceToJSON(json: any): WordSentence {
    return WordSentenceToJSONTyped(json, false);
}

export function WordSentenceToJSONTyped(value?: WordSentence | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'translations': value['translations'],
    };
}

