/* tslint:disable */
/* eslint-disable */
/**
 * BeyondTranslate API
 * HTTP API for translation and dictionary lookups.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WordPhrase
 */
export interface WordPhrase {
    /**
     * 
     * @type {string}
     * @memberof WordPhrase
     */
    text: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WordPhrase
     */
    translations: Array<string>;
}

/**
 * Check if a given object implements the WordPhrase interface.
 */
export function instanceOfWordPhrase(value: object): value is WordPhrase {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('translations' in value) || value['translations'] === undefined) return false;
    return true;
}

export function WordPhraseFromJSON(json: any): WordPhrase {
    return WordPhraseFromJSONTyped(json, false);
}

export function WordPhraseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordPhrase {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'translations': json['translations'],
    };
}

export function WordPhraseToJSON(json: any): WordPhrase {
    return WordPhraseToJSONTyped(json, false);
}

export function WordPhraseToJSONTyped(value?: WordPhrase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'translations': value['translations'],
    };
}

