/* tslint:disable */
/* eslint-disable */
/**
 * BeyondTranslate API
 * HTTP API for translation and dictionary lookups.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WordDefinition
 */
export interface WordDefinition {
    /**
     * 
     * @type {string}
     * @memberof WordDefinition
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof WordDefinition
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WordDefinition
     */
    values?: Array<string>;
}

/**
 * Check if a given object implements the WordDefinition interface.
 */
export function instanceOfWordDefinition(value: object): value is WordDefinition {
    return true;
}

export function WordDefinitionFromJSON(json: any): WordDefinition {
    return WordDefinitionFromJSONTyped(json, false);
}

export function WordDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordDefinition {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'name': json['name'] == null ? undefined : json['name'],
        'values': json['values'] == null ? undefined : json['values'],
    };
}

export function WordDefinitionToJSON(json: any): WordDefinition {
    return WordDefinitionToJSONTyped(json, false);
}

export function WordDefinitionToJSONTyped(value?: WordDefinition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'name': value['name'],
        'values': value['values'],
    };
}

