// This file is automatically generated. Do not edit by hand.

import Foundation

struct LocaleKey: RawRepresentable {
  let rawValue: String

  init(rawValue: String) {
    self.rawValue = rawValue
  }

  init(_ rawValue: String) {
    self.rawValue = rawValue
  }
}

extension LocaleKey {
  func tr() -> String {
    AppLocale.shared.localizedString(rawValue)
  }

  func tr(_ args: CVarArg...) -> String {
    var template = tr()
    for _ in args {
      template = template.replacingOccurrences(
        of: "{}", with: "%@", options: [], range: template.range(of: "{}"))
    }
    return String(format: template, locale: Locale.current, arguments: args)
  }
}

enum LocaleKeys {
  enum common {
    enum app {
      static let name = LocaleKey("common.app.name")
    }
    enum button {
      static let add = LocaleKey("common.button.add")
      static let cancel = LocaleKey("common.button.cancel")
      static let delete = LocaleKey("common.button.delete")
      static let edit = LocaleKey("common.button.edit")
      static let manage = LocaleKey("common.button.manage")
      static let ok = LocaleKey("common.button.ok")
      static let save = LocaleKey("common.button.save")
    }
    enum feedback {
      static let copied = LocaleKey("common.feedback.copied")
    }
    enum language {
      static let af = LocaleKey("common.language.af")
      static let am = LocaleKey("common.language.am")
      static let ar = LocaleKey("common.language.ar")
      static let az = LocaleKey("common.language.az")
      static let be = LocaleKey("common.language.be")
      static let bg = LocaleKey("common.language.bg")
      static let bn = LocaleKey("common.language.bn")
      static let bs = LocaleKey("common.language.bs")
      static let ca = LocaleKey("common.language.ca")
      static let ceb = LocaleKey("common.language.ceb")
      static let co = LocaleKey("common.language.co")
      static let cs = LocaleKey("common.language.cs")
      static let cy = LocaleKey("common.language.cy")
      static let da = LocaleKey("common.language.da")
      static let de = LocaleKey("common.language.de")
      static let el = LocaleKey("common.language.el")
      static let en = LocaleKey("common.language.en")
      static let eo = LocaleKey("common.language.eo")
      static let es = LocaleKey("common.language.es")
      static let et = LocaleKey("common.language.et")
      static let eu = LocaleKey("common.language.eu")
      static let fa = LocaleKey("common.language.fa")
      static let fi = LocaleKey("common.language.fi")
      static let fr = LocaleKey("common.language.fr")
      static let fy = LocaleKey("common.language.fy")
      static let ga = LocaleKey("common.language.ga")
      static let gd = LocaleKey("common.language.gd")
      static let gl = LocaleKey("common.language.gl")
      static let gu = LocaleKey("common.language.gu")
      static let ha = LocaleKey("common.language.ha")
      static let haw = LocaleKey("common.language.haw")
      static let he = LocaleKey("common.language.he")
      static let hi = LocaleKey("common.language.hi")
      static let hmn = LocaleKey("common.language.hmn")
      static let hr = LocaleKey("common.language.hr")
      static let ht = LocaleKey("common.language.ht")
      static let hu = LocaleKey("common.language.hu")
      static let hy = LocaleKey("common.language.hy")
      static let id = LocaleKey("common.language.id")
      static let ig = LocaleKey("common.language.ig")
      static let `is` = LocaleKey("common.language.is")
      static let it = LocaleKey("common.language.it")
      static let iw = LocaleKey("common.language.iw")
      static let ja = LocaleKey("common.language.ja")
      static let jw = LocaleKey("common.language.jw")
      static let ka = LocaleKey("common.language.ka")
      static let kk = LocaleKey("common.language.kk")
      static let km = LocaleKey("common.language.km")
      static let kn = LocaleKey("common.language.kn")
      static let ko = LocaleKey("common.language.ko")
      static let ku = LocaleKey("common.language.ku")
      static let ky = LocaleKey("common.language.ky")
      static let la = LocaleKey("common.language.la")
      static let lb = LocaleKey("common.language.lb")
      static let lo = LocaleKey("common.language.lo")
      static let lt = LocaleKey("common.language.lt")
      static let lv = LocaleKey("common.language.lv")
      static let mg = LocaleKey("common.language.mg")
      static let mi = LocaleKey("common.language.mi")
      static let mk = LocaleKey("common.language.mk")
      static let ml = LocaleKey("common.language.ml")
      static let mn = LocaleKey("common.language.mn")
      static let mr = LocaleKey("common.language.mr")
      static let ms = LocaleKey("common.language.ms")
      static let mt = LocaleKey("common.language.mt")
      static let my = LocaleKey("common.language.my")
      static let ne = LocaleKey("common.language.ne")
      static let nl = LocaleKey("common.language.nl")
      static let no = LocaleKey("common.language.no")
      static let ny = LocaleKey("common.language.ny")
      static let or = LocaleKey("common.language.or")
      static let pa = LocaleKey("common.language.pa")
      static let pl = LocaleKey("common.language.pl")
      static let ps = LocaleKey("common.language.ps")
      static let pt = LocaleKey("common.language.pt")
      static let ro = LocaleKey("common.language.ro")
      static let ru = LocaleKey("common.language.ru")
      static let rw = LocaleKey("common.language.rw")
      static let sd = LocaleKey("common.language.sd")
      static let si = LocaleKey("common.language.si")
      static let sk = LocaleKey("common.language.sk")
      static let sl = LocaleKey("common.language.sl")
      static let sm = LocaleKey("common.language.sm")
      static let sn = LocaleKey("common.language.sn")
      static let so = LocaleKey("common.language.so")
      static let sq = LocaleKey("common.language.sq")
      static let sr = LocaleKey("common.language.sr")
      static let st = LocaleKey("common.language.st")
      static let su = LocaleKey("common.language.su")
      static let sv = LocaleKey("common.language.sv")
      static let sw = LocaleKey("common.language.sw")
      static let ta = LocaleKey("common.language.ta")
      static let te = LocaleKey("common.language.te")
      static let tg = LocaleKey("common.language.tg")
      static let th = LocaleKey("common.language.th")
      static let tk = LocaleKey("common.language.tk")
      static let tl = LocaleKey("common.language.tl")
      static let tr = LocaleKey("common.language.tr")
      static let tt = LocaleKey("common.language.tt")
      static let ug = LocaleKey("common.language.ug")
      static let uk = LocaleKey("common.language.uk")
      static let ur = LocaleKey("common.language.ur")
      static let uz = LocaleKey("common.language.uz")
      static let vi = LocaleKey("common.language.vi")
      static let xh = LocaleKey("common.language.xh")
      static let yi = LocaleKey("common.language.yi")
      static let yo = LocaleKey("common.language.yo")
      static let zh = LocaleKey("common.language.zh")
      static let zhCN = LocaleKey("common.language.zh_CN")
      static let zhTW = LocaleKey("common.language.zh_TW")
      static let zu = LocaleKey("common.language.zu")
    }
    enum placeholder {
      static let choose = LocaleKey("common.placeholder.choose")
    }
  }
  enum miniTranslator {
    enum button {
      static let clear = LocaleKey("mini_translator.button.clear")
      static let translate = LocaleKey("mini_translator.button.translate")
    }
    enum input {
      static let extractingText = LocaleKey("mini_translator.input.extracting_text")
      static let hint = LocaleKey("mini_translator.input.hint")
    }
    enum limitedBanner {
      enum button {
        static let allow = LocaleKey("mini_translator.limited_banner.button.allow")
        static let checkAgain = LocaleKey("mini_translator.limited_banner.button.check_again")
        static let goSettings = LocaleKey("mini_translator.limited_banner.button.go_settings")
      }
      enum message {
        static let allAccessAllowed = LocaleKey(
          "mini_translator.limited_banner.message.all_access_allowed")
        static let allAccessNotAllowed = LocaleKey(
          "mini_translator.limited_banner.message.all_access_not_allowed")
        static let allowAccessTip = LocaleKey(
          "mini_translator.limited_banner.message.allow_access_tip")
      }
      enum permission {
        static let screenCapture = LocaleKey(
          "mini_translator.limited_banner.permission.screen_capture")
        static let screenSelection = LocaleKey(
          "mini_translator.limited_banner.permission.screen_selection")
      }
      static let title = LocaleKey("mini_translator.limited_banner.title")
      enum tooltip {
        static let help = LocaleKey("mini_translator.limited_banner.tooltip.help")
      }
    }
    enum message {
      static let captureScreenAreaCanceled = LocaleKey(
        "mini_translator.message.capture_screen_area_canceled")
      static let pleaseEnterWordOrText = LocaleKey(
        "mini_translator.message.please_enter_word_or_text")
    }
    enum toolbar {
      enum tooltip {
        static let extractTextFromClipboard = LocaleKey(
          "mini_translator.toolbar.tooltip.extract_text_from_clipboard")
        static let extractTextFromScreenCapture = LocaleKey(
          "mini_translator.toolbar.tooltip.extract_text_from_screen_capture")
        static let translationMode = LocaleKey("mini_translator.toolbar.tooltip.translation_mode")
      }
    }
    enum updateBanner {
      enum button {
        static let update = LocaleKey("mini_translator.update_banner.button.update")
      }
      static let foundNewVersion = LocaleKey("mini_translator.update_banner.found_new_version")
    }
  }
  enum ocr {
    enum engine {
      static let builtIn = LocaleKey("ocr.engine.built_in")
      static let tesseract = LocaleKey("ocr.engine.tesseract")
      static let youdao = LocaleKey("ocr.engine.youdao")
    }
  }
  enum provider {
    static let baidu = LocaleKey("provider.baidu")
    static let caiyun = LocaleKey("provider.caiyun")
    static let deepl = LocaleKey("provider.deepl")
    static let google = LocaleKey("provider.google")
    static let ibmwatson = LocaleKey("provider.ibmwatson")
    static let iciba = LocaleKey("provider.iciba")
    static let openai = LocaleKey("provider.openai")
    static let sogou = LocaleKey("provider.sogou")
    static let tencent = LocaleKey("provider.tencent")
    static let youdao = LocaleKey("provider.youdao")
  }
  enum settings {
    enum advanced {
      static let empty = LocaleKey("settings.advanced.empty")
      static let title = LocaleKey("settings.advanced.title")
    }
    enum appearance {
      static let title = LocaleKey("settings.appearance.title")
    }
    enum empty {
      static let message = LocaleKey("settings.empty.message")
      static let title = LocaleKey("settings.empty.title")
    }
    enum exitAppDialog {
      static let title = LocaleKey("settings.exit_app_dialog.title")
    }
    enum general {
      static let title = LocaleKey("settings.general.title")
    }
    enum input {
      static let title = LocaleKey("settings.input.title")
    }
    enum option {
      static let builtInOcr = LocaleKey("settings.option.built_in_ocr")
      static let chinese = LocaleKey("settings.option.chinese")
      static let english = LocaleKey("settings.option.english")
      static let granted = LocaleKey("settings.option.granted")
      static let noServicesAvailable = LocaleKey("settings.option.no_services_available")
      static let none = LocaleKey("settings.option.none")
      static let tesseract = LocaleKey("settings.option.tesseract")
      static let youdaoOcr = LocaleKey("settings.option.youdao_ocr")
    }
    enum others {
      static let title = LocaleKey("settings.others.title")
    }
    enum preference {
      static let about = LocaleKey("settings.preference.about")
      static let addTarget = LocaleKey("settings.preference.add_target")
      static let appLanguage = LocaleKey("settings.preference.app_language")
      static let autoCopyDetectedText = LocaleKey("settings.preference.auto_copy_detected_text")
      static let defaultDirectoryService = LocaleKey(
        "settings.preference.default_directory_service")
      static let defaultExtractTextService = LocaleKey(
        "settings.preference.default_extract_text_service")
      static let defaultTranslationService = LocaleKey(
        "settings.preference.default_translation_service")
      static let directory = LocaleKey("settings.preference.directory")
      static let doubleClickCopyResult = LocaleKey("settings.preference.double_click_copy_result")
      static let engines = LocaleKey("settings.preference.engines")
      static let exitApp = LocaleKey("settings.preference.exit_app")
      static let extractText = LocaleKey("settings.preference.extract_text")
      static let interface = LocaleKey("settings.preference.interface")
      static let keyboardShortcuts = LocaleKey("settings.preference.keyboard_shortcuts")
      static let launchAtStartup = LocaleKey("settings.preference.launch_at_startup")
      static let ocrEngines = LocaleKey("settings.preference.ocr_engines")
      static let permissions = LocaleKey("settings.preference.permissions")
      static let showMenuBar = LocaleKey("settings.preference.show_menu_bar")
      static let submitWithEnter = LocaleKey("settings.preference.submit_with_enter")
      static let submitWithMetaEnter = LocaleKey("settings.preference.submit_with_meta_enter")
      static let submitWithMetaEnterMac = LocaleKey(
        "settings.preference.submit_with_meta_enter_mac")
      static let themeMode = LocaleKey("settings.preference.theme_mode")
      static let translate = LocaleKey("settings.preference.translate")
      static let translation = LocaleKey("settings.preference.translation")
      static let translationMode = LocaleKey("settings.preference.translation_mode")
      static let translationTarget = LocaleKey("settings.preference.translation_target")
      static let yourPlan = LocaleKey("settings.preference.your_plan")
    }
    enum providers {
      static let add = LocaleKey("settings.providers.add")
      static let addTitle = LocaleKey("settings.providers.add_title")
      enum capability {
        static let dictionary = LocaleKey("settings.providers.capability.dictionary")
        static let translation = LocaleKey("settings.providers.capability.translation")
      }
      static let deleteConfirm = LocaleKey("settings.providers.delete_confirm")
      static let deleteMessage = LocaleKey("settings.providers.delete_message")
      static let deleteTitle = LocaleKey("settings.providers.delete_title")
      enum description {
        static let all = LocaleKey("settings.providers.description.all")
        static let dictionary = LocaleKey("settings.providers.description.dictionary")
        static let fallback = LocaleKey("settings.providers.description.fallback")
        static let translation = LocaleKey("settings.providers.description.translation")
      }
      static let editTitle = LocaleKey("settings.providers.edit_title")
      static let empty = LocaleKey("settings.providers.empty")
      static let error = LocaleKey("settings.providers.error")
      static let help = LocaleKey("settings.providers.help")
      static let helpEdit = LocaleKey("settings.providers.help_edit")
      static let id = LocaleKey("settings.providers.id")
      static let idPlaceholder = LocaleKey("settings.providers.id_placeholder")
      static let intro = LocaleKey("settings.providers.intro")
      static let introWarning = LocaleKey("settings.providers.intro_warning")
      static let loading = LocaleKey("settings.providers.loading")
      static let noServices = LocaleKey("settings.providers.no_services")
      static let services = LocaleKey("settings.providers.services")
      static let title = LocaleKey("settings.providers.title")
      static let type = LocaleKey("settings.providers.type")
    }
    enum serviceIntegration {
      static let title = LocaleKey("settings.service_integration.title")
    }
    enum shortcut {
      static let extractCapture = LocaleKey("settings.shortcut.extract_capture")
      static let extractClipboard = LocaleKey("settings.shortcut.extract_clipboard")
      static let extractSelection = LocaleKey("settings.shortcut.extract_selection")
      static let extractText = LocaleKey("settings.shortcut.extract_text")
      static let hide = LocaleKey("settings.shortcut.hide")
      static let inputAssist = LocaleKey("settings.shortcut.input_assist")
      static let section = LocaleKey("settings.shortcut.section")
      static let showOrHide = LocaleKey("settings.shortcut.show_or_hide")
      static let translateInput = LocaleKey("settings.shortcut.translate_input")
    }
    enum shortcuts {
      static let title = LocaleKey("settings.shortcuts.title")
    }
    static let title = LocaleKey("settings.title")
    static let version = LocaleKey("settings.version")
  }
  enum shortcuts {
    enum recordDialog {
      static let title = LocaleKey("shortcuts.record_dialog.title")
    }
  }
  enum theme {
    enum mode {
      static let dark = LocaleKey("theme.mode.dark")
      static let light = LocaleKey("theme.mode.light")
      static let system = LocaleKey("theme.mode.system")
    }
  }
  enum translation {
    enum engineScope {
      static let detectLanguage = LocaleKey("translation.engine_scope.detect_language")
      static let lookup = LocaleKey("translation.engine_scope.lookup")
      static let translate = LocaleKey("translation.engine_scope.translate")
    }
    enum mode {
      static let auto = LocaleKey("translation.mode.auto")
      static let manual = LocaleKey("translation.mode.manual")
    }
    enum wordPronunciation {
      static let uk = LocaleKey("translation.word_pronunciation.uk")
      static let us = LocaleKey("translation.word_pronunciation.us")
    }
  }
  enum tray {
    enum contextMenu {
      enum discussion {
        static let discordServer = LocaleKey("tray.context_menu.discussion.discord_server")
        static let qqGroup = LocaleKey("tray.context_menu.discussion.qq_group")
        static let title = LocaleKey("tray.context_menu.discussion.title")
      }
      static let quickStartGuide = LocaleKey("tray.context_menu.quick_start_guide")
      static let quitApp = LocaleKey("tray.context_menu.quit_app")
      static let show = LocaleKey("tray.context_menu.show")
    }
  }
}
