// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

import 'api/mirrors.dart';
import 'api/runtime.dart';
import 'domain/settings.dart';
import 'frb_generated.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RuntimePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimePtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_RuntimeDictionaryPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionaryPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_RuntimeSettingsPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettingsPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_RuntimeTranslationPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslationPtr;

  @protected
  Runtime
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntime(
          dynamic raw);

  @protected
  RuntimeDictionary
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionary(
          dynamic raw);

  @protected
  RuntimeSettings
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettings(
          dynamic raw);

  @protected
  RuntimeTranslation
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslation(
          dynamic raw);

  @protected
  Runtime
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntime(
          dynamic raw);

  @protected
  RuntimeDictionary
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionary(
          dynamic raw);

  @protected
  RuntimeSettings
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettings(
          dynamic raw);

  @protected
  RuntimeTranslation
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslation(
          dynamic raw);

  @protected
  Runtime
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntime(
          dynamic raw);

  @protected
  RuntimeDictionary
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionary(
          dynamic raw);

  @protected
  RuntimeSettings
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettings(
          dynamic raw);

  @protected
  RuntimeTranslation
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslation(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  LookUpRequest dco_decode_box_autoadd_look_up_request(dynamic raw);

  @protected
  RustProviderEntry dco_decode_box_autoadd_rust_provider_entry(dynamic raw);

  @protected
  TranslateRequest dco_decode_box_autoadd_translate_request(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RustProviderEntry> dco_decode_list_rust_provider_entry(dynamic raw);

  @protected
  List<TextTranslation> dco_decode_list_text_translation(dynamic raw);

  @protected
  List<WordDefinition> dco_decode_list_word_definition(dynamic raw);

  @protected
  List<WordImage> dco_decode_list_word_image(dynamic raw);

  @protected
  List<WordPhrase> dco_decode_list_word_phrase(dynamic raw);

  @protected
  List<WordPronunciation> dco_decode_list_word_pronunciation(dynamic raw);

  @protected
  List<WordSentence> dco_decode_list_word_sentence(dynamic raw);

  @protected
  List<WordTag> dco_decode_list_word_tag(dynamic raw);

  @protected
  List<WordTense> dco_decode_list_word_tense(dynamic raw);

  @protected
  LookUpRequest dco_decode_look_up_request(dynamic raw);

  @protected
  LookUpResponse dco_decode_look_up_response(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  RustProviderEntry? dco_decode_opt_box_autoadd_rust_provider_entry(
      dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  List<WordDefinition>? dco_decode_opt_list_word_definition(dynamic raw);

  @protected
  List<WordImage>? dco_decode_opt_list_word_image(dynamic raw);

  @protected
  List<WordPhrase>? dco_decode_opt_list_word_phrase(dynamic raw);

  @protected
  List<WordPronunciation>? dco_decode_opt_list_word_pronunciation(dynamic raw);

  @protected
  List<WordSentence>? dco_decode_opt_list_word_sentence(dynamic raw);

  @protected
  List<WordTag>? dco_decode_opt_list_word_tag(dynamic raw);

  @protected
  List<WordTense>? dco_decode_opt_list_word_tense(dynamic raw);

  @protected
  RustProviderEntry dco_decode_rust_provider_entry(dynamic raw);

  @protected
  RustSettingsDto dco_decode_rust_settings_dto(dynamic raw);

  @protected
  TextTranslation dco_decode_text_translation(dynamic raw);

  @protected
  TranslateRequest dco_decode_translate_request(dynamic raw);

  @protected
  TranslateResponse dco_decode_translate_response(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WordDefinition dco_decode_word_definition(dynamic raw);

  @protected
  WordImage dco_decode_word_image(dynamic raw);

  @protected
  WordPhrase dco_decode_word_phrase(dynamic raw);

  @protected
  WordPronunciation dco_decode_word_pronunciation(dynamic raw);

  @protected
  WordSentence dco_decode_word_sentence(dynamic raw);

  @protected
  WordTag dco_decode_word_tag(dynamic raw);

  @protected
  WordTense dco_decode_word_tense(dynamic raw);

  @protected
  Runtime
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntime(
          SseDeserializer deserializer);

  @protected
  RuntimeDictionary
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionary(
          SseDeserializer deserializer);

  @protected
  RuntimeSettings
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettings(
          SseDeserializer deserializer);

  @protected
  RuntimeTranslation
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslation(
          SseDeserializer deserializer);

  @protected
  Runtime
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntime(
          SseDeserializer deserializer);

  @protected
  RuntimeDictionary
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionary(
          SseDeserializer deserializer);

  @protected
  RuntimeSettings
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettings(
          SseDeserializer deserializer);

  @protected
  RuntimeTranslation
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslation(
          SseDeserializer deserializer);

  @protected
  Runtime
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntime(
          SseDeserializer deserializer);

  @protected
  RuntimeDictionary
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionary(
          SseDeserializer deserializer);

  @protected
  RuntimeSettings
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettings(
          SseDeserializer deserializer);

  @protected
  RuntimeTranslation
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslation(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  LookUpRequest sse_decode_box_autoadd_look_up_request(
      SseDeserializer deserializer);

  @protected
  RustProviderEntry sse_decode_box_autoadd_rust_provider_entry(
      SseDeserializer deserializer);

  @protected
  TranslateRequest sse_decode_box_autoadd_translate_request(
      SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RustProviderEntry> sse_decode_list_rust_provider_entry(
      SseDeserializer deserializer);

  @protected
  List<TextTranslation> sse_decode_list_text_translation(
      SseDeserializer deserializer);

  @protected
  List<WordDefinition> sse_decode_list_word_definition(
      SseDeserializer deserializer);

  @protected
  List<WordImage> sse_decode_list_word_image(SseDeserializer deserializer);

  @protected
  List<WordPhrase> sse_decode_list_word_phrase(SseDeserializer deserializer);

  @protected
  List<WordPronunciation> sse_decode_list_word_pronunciation(
      SseDeserializer deserializer);

  @protected
  List<WordSentence> sse_decode_list_word_sentence(
      SseDeserializer deserializer);

  @protected
  List<WordTag> sse_decode_list_word_tag(SseDeserializer deserializer);

  @protected
  List<WordTense> sse_decode_list_word_tense(SseDeserializer deserializer);

  @protected
  LookUpRequest sse_decode_look_up_request(SseDeserializer deserializer);

  @protected
  LookUpResponse sse_decode_look_up_response(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  RustProviderEntry? sse_decode_opt_box_autoadd_rust_provider_entry(
      SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  List<WordDefinition>? sse_decode_opt_list_word_definition(
      SseDeserializer deserializer);

  @protected
  List<WordImage>? sse_decode_opt_list_word_image(SseDeserializer deserializer);

  @protected
  List<WordPhrase>? sse_decode_opt_list_word_phrase(
      SseDeserializer deserializer);

  @protected
  List<WordPronunciation>? sse_decode_opt_list_word_pronunciation(
      SseDeserializer deserializer);

  @protected
  List<WordSentence>? sse_decode_opt_list_word_sentence(
      SseDeserializer deserializer);

  @protected
  List<WordTag>? sse_decode_opt_list_word_tag(SseDeserializer deserializer);

  @protected
  List<WordTense>? sse_decode_opt_list_word_tense(SseDeserializer deserializer);

  @protected
  RustProviderEntry sse_decode_rust_provider_entry(
      SseDeserializer deserializer);

  @protected
  RustSettingsDto sse_decode_rust_settings_dto(SseDeserializer deserializer);

  @protected
  TextTranslation sse_decode_text_translation(SseDeserializer deserializer);

  @protected
  TranslateRequest sse_decode_translate_request(SseDeserializer deserializer);

  @protected
  TranslateResponse sse_decode_translate_response(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WordDefinition sse_decode_word_definition(SseDeserializer deserializer);

  @protected
  WordImage sse_decode_word_image(SseDeserializer deserializer);

  @protected
  WordPhrase sse_decode_word_phrase(SseDeserializer deserializer);

  @protected
  WordPronunciation sse_decode_word_pronunciation(SseDeserializer deserializer);

  @protected
  WordSentence sse_decode_word_sentence(SseDeserializer deserializer);

  @protected
  WordTag sse_decode_word_tag(SseDeserializer deserializer);

  @protected
  WordTense sse_decode_word_tense(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntime(
          Runtime self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionary(
          RuntimeDictionary self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettings(
          RuntimeSettings self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslation(
          RuntimeTranslation self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntime(
          Runtime self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionary(
          RuntimeDictionary self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettings(
          RuntimeSettings self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslation(
          RuntimeTranslation self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntime(
          Runtime self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionary(
          RuntimeDictionary self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettings(
          RuntimeSettings self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslation(
          RuntimeTranslation self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_look_up_request(
      LookUpRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_rust_provider_entry(
      RustProviderEntry self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_translate_request(
      TranslateRequest self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_rust_provider_entry(
      List<RustProviderEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_text_translation(
      List<TextTranslation> self, SseSerializer serializer);

  @protected
  void sse_encode_list_word_definition(
      List<WordDefinition> self, SseSerializer serializer);

  @protected
  void sse_encode_list_word_image(
      List<WordImage> self, SseSerializer serializer);

  @protected
  void sse_encode_list_word_phrase(
      List<WordPhrase> self, SseSerializer serializer);

  @protected
  void sse_encode_list_word_pronunciation(
      List<WordPronunciation> self, SseSerializer serializer);

  @protected
  void sse_encode_list_word_sentence(
      List<WordSentence> self, SseSerializer serializer);

  @protected
  void sse_encode_list_word_tag(List<WordTag> self, SseSerializer serializer);

  @protected
  void sse_encode_list_word_tense(
      List<WordTense> self, SseSerializer serializer);

  @protected
  void sse_encode_look_up_request(LookUpRequest self, SseSerializer serializer);

  @protected
  void sse_encode_look_up_response(
      LookUpResponse self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_rust_provider_entry(
      RustProviderEntry? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_word_definition(
      List<WordDefinition>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_word_image(
      List<WordImage>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_word_phrase(
      List<WordPhrase>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_word_pronunciation(
      List<WordPronunciation>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_word_sentence(
      List<WordSentence>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_word_tag(
      List<WordTag>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_word_tense(
      List<WordTense>? self, SseSerializer serializer);

  @protected
  void sse_encode_rust_provider_entry(
      RustProviderEntry self, SseSerializer serializer);

  @protected
  void sse_encode_rust_settings_dto(
      RustSettingsDto self, SseSerializer serializer);

  @protected
  void sse_encode_text_translation(
      TextTranslation self, SseSerializer serializer);

  @protected
  void sse_encode_translate_request(
      TranslateRequest self, SseSerializer serializer);

  @protected
  void sse_encode_translate_response(
      TranslateResponse self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_word_definition(
      WordDefinition self, SseSerializer serializer);

  @protected
  void sse_encode_word_image(WordImage self, SseSerializer serializer);

  @protected
  void sse_encode_word_phrase(WordPhrase self, SseSerializer serializer);

  @protected
  void sse_encode_word_pronunciation(
      WordPronunciation self, SseSerializer serializer);

  @protected
  void sse_encode_word_sentence(WordSentence self, SseSerializer serializer);

  @protected
  void sse_encode_word_tag(WordTag self, SseSerializer serializer);

  @protected
  void sse_encode_word_tense(WordTense self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntime(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntime(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_beyondtranslate_desktop_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntime');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntime =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntime(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntime(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_beyondtranslate_desktop_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntime');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntime =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionary(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionary(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionaryPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_beyondtranslate_desktop_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionary');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionary =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionaryPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionary(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionary(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionaryPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_beyondtranslate_desktop_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionary');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionary =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeDictionaryPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettings(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettings(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettingsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_beyondtranslate_desktop_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettings');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettings =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettingsPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettings(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettings(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettingsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_beyondtranslate_desktop_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettings');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettings =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeSettingsPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslation(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslation(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslationPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_beyondtranslate_desktop_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslation');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslation =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslationPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslation(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslation(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslationPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_beyondtranslate_desktop_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslation');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslation =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeTranslationPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
