// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'api/simple.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1273871166;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'beyondtranslate_desktop_rust',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSimpleInitApp();

  Future<RustLookupDebugResponse> crateApiSimpleLookupWithRuntime(
      {required RustLookupDebugRequest request});

  Future<RustTranslateDebugResponse> crateApiSimpleTranslateWithRuntime(
      {required RustTranslateDebugRequest request});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<RustLookupDebugResponse> crateApiSimpleLookupWithRuntime(
      {required RustLookupDebugRequest request}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_rust_lookup_debug_request(request, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_rust_lookup_debug_response,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleLookupWithRuntimeConstMeta,
      argValues: [request],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleLookupWithRuntimeConstMeta =>
      const TaskConstMeta(
        debugName: "lookup_with_runtime",
        argNames: ["request"],
      );

  @override
  Future<RustTranslateDebugResponse> crateApiSimpleTranslateWithRuntime(
      {required RustTranslateDebugRequest request}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_rust_translate_debug_request(
            request, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_rust_translate_debug_response,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSimpleTranslateWithRuntimeConstMeta,
      argValues: [request],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleTranslateWithRuntimeConstMeta =>
      const TaskConstMeta(
        debugName: "translate_with_runtime",
        argNames: ["request"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  RustLookupDebugRequest dco_decode_box_autoadd_rust_lookup_debug_request(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rust_lookup_debug_request(raw);
  }

  @protected
  RustTranslateDebugRequest dco_decode_box_autoadd_rust_translate_debug_request(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rust_translate_debug_request(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  RustLookupDebugRequest dco_decode_rust_lookup_debug_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RustLookupDebugRequest(
      providerType: dco_decode_String(arr[0]),
      providerConfigYaml: dco_decode_String(arr[1]),
      sourceLanguage: dco_decode_String(arr[2]),
      targetLanguage: dco_decode_String(arr[3]),
      word: dco_decode_String(arr[4]),
    );
  }

  @protected
  RustLookupDebugResponse dco_decode_rust_lookup_debug_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RustLookupDebugResponse(
      providerType: dco_decode_String(arr[0]),
      word: dco_decode_opt_String(arr[1]),
      definitions: dco_decode_list_String(arr[2]),
      pronunciations: dco_decode_list_String(arr[3]),
      tenses: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  RustTranslateDebugRequest dco_decode_rust_translate_debug_request(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return RustTranslateDebugRequest(
      providerType: dco_decode_String(arr[0]),
      providerConfigYaml: dco_decode_String(arr[1]),
      sourceLanguage: dco_decode_opt_String(arr[2]),
      targetLanguage: dco_decode_String(arr[3]),
      text: dco_decode_String(arr[4]),
    );
  }

  @protected
  RustTranslateDebugResponse dco_decode_rust_translate_debug_response(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RustTranslateDebugResponse(
      providerType: dco_decode_String(arr[0]),
      translations: dco_decode_list_String(arr[1]),
      detectedSourceLanguage: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  RustLookupDebugRequest sse_decode_box_autoadd_rust_lookup_debug_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rust_lookup_debug_request(deserializer));
  }

  @protected
  RustTranslateDebugRequest sse_decode_box_autoadd_rust_translate_debug_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rust_translate_debug_request(deserializer));
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RustLookupDebugRequest sse_decode_rust_lookup_debug_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_providerType = sse_decode_String(deserializer);
    var var_providerConfigYaml = sse_decode_String(deserializer);
    var var_sourceLanguage = sse_decode_String(deserializer);
    var var_targetLanguage = sse_decode_String(deserializer);
    var var_word = sse_decode_String(deserializer);
    return RustLookupDebugRequest(
        providerType: var_providerType,
        providerConfigYaml: var_providerConfigYaml,
        sourceLanguage: var_sourceLanguage,
        targetLanguage: var_targetLanguage,
        word: var_word);
  }

  @protected
  RustLookupDebugResponse sse_decode_rust_lookup_debug_response(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_providerType = sse_decode_String(deserializer);
    var var_word = sse_decode_opt_String(deserializer);
    var var_definitions = sse_decode_list_String(deserializer);
    var var_pronunciations = sse_decode_list_String(deserializer);
    var var_tenses = sse_decode_list_String(deserializer);
    return RustLookupDebugResponse(
        providerType: var_providerType,
        word: var_word,
        definitions: var_definitions,
        pronunciations: var_pronunciations,
        tenses: var_tenses);
  }

  @protected
  RustTranslateDebugRequest sse_decode_rust_translate_debug_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_providerType = sse_decode_String(deserializer);
    var var_providerConfigYaml = sse_decode_String(deserializer);
    var var_sourceLanguage = sse_decode_opt_String(deserializer);
    var var_targetLanguage = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    return RustTranslateDebugRequest(
        providerType: var_providerType,
        providerConfigYaml: var_providerConfigYaml,
        sourceLanguage: var_sourceLanguage,
        targetLanguage: var_targetLanguage,
        text: var_text);
  }

  @protected
  RustTranslateDebugResponse sse_decode_rust_translate_debug_response(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_providerType = sse_decode_String(deserializer);
    var var_translations = sse_decode_list_String(deserializer);
    var var_detectedSourceLanguage = sse_decode_opt_String(deserializer);
    return RustTranslateDebugResponse(
        providerType: var_providerType,
        translations: var_translations,
        detectedSourceLanguage: var_detectedSourceLanguage);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_rust_lookup_debug_request(
      RustLookupDebugRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rust_lookup_debug_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_rust_translate_debug_request(
      RustTranslateDebugRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rust_translate_debug_request(self, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_rust_lookup_debug_request(
      RustLookupDebugRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.providerType, serializer);
    sse_encode_String(self.providerConfigYaml, serializer);
    sse_encode_String(self.sourceLanguage, serializer);
    sse_encode_String(self.targetLanguage, serializer);
    sse_encode_String(self.word, serializer);
  }

  @protected
  void sse_encode_rust_lookup_debug_response(
      RustLookupDebugResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.providerType, serializer);
    sse_encode_opt_String(self.word, serializer);
    sse_encode_list_String(self.definitions, serializer);
    sse_encode_list_String(self.pronunciations, serializer);
    sse_encode_list_String(self.tenses, serializer);
  }

  @protected
  void sse_encode_rust_translate_debug_request(
      RustTranslateDebugRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.providerType, serializer);
    sse_encode_String(self.providerConfigYaml, serializer);
    sse_encode_opt_String(self.sourceLanguage, serializer);
    sse_encode_String(self.targetLanguage, serializer);
    sse_encode_String(self.text, serializer);
  }

  @protected
  void sse_encode_rust_translate_debug_response(
      RustTranslateDebugResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.providerType, serializer);
    sse_encode_list_String(self.translations, serializer);
    sse_encode_opt_String(self.detectedSourceLanguage, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
