/* tslint:disable */
/* eslint-disable */
/**
 * BeyondTranslate API
 * HTTP API for translation and dictionary lookups.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponseEnvelope,
    ErrorResponseEnvelopeFromJSON,
    ErrorResponseEnvelopeToJSON,
} from '../models/ErrorResponseEnvelope';
import {
    type LookUpRequest,
    LookUpRequestFromJSON,
    LookUpRequestToJSON,
} from '../models/LookUpRequest';
import {
    type LookUpResponseEnvelope,
    LookUpResponseEnvelopeFromJSON,
    LookUpResponseEnvelopeToJSON,
} from '../models/LookUpResponseEnvelope';

export interface LookupDictionaryEntryRequest {
    provider: LookupDictionaryEntryProviderEnum;
    lookUpRequest: LookUpRequest;
}

/**
 * 
 */
export class DictionariesApi extends runtime.BaseAPI {

    /**
     * Creates request options for lookupDictionaryEntry without sending the request
     */
    async lookupDictionaryEntryRequestOpts(requestParameters: LookupDictionaryEntryRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['provider'] == null) {
            throw new runtime.RequiredError(
                'provider',
                'Required parameter "provider" was null or undefined when calling lookupDictionaryEntry().'
            );
        }

        if (requestParameters['lookUpRequest'] == null) {
            throw new runtime.RequiredError(
                'lookUpRequest',
                'Required parameter "lookUpRequest" was null or undefined when calling lookupDictionaryEntry().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/dictionaries/{provider}/lookup`;
        urlPath = urlPath.replace('{provider}', encodeURIComponent(String(requestParameters['provider'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LookUpRequestToJSON(requestParameters['lookUpRequest']),
        };
    }

    /**
     * Lookup a dictionary entry
     */
    async lookupDictionaryEntryRaw(requestParameters: LookupDictionaryEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LookUpResponseEnvelope>> {
        const requestOptions = await this.lookupDictionaryEntryRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LookUpResponseEnvelopeFromJSON(jsonValue));
    }

    /**
     * Lookup a dictionary entry
     */
    async lookupDictionaryEntry(requestParameters: LookupDictionaryEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LookUpResponseEnvelope> {
        const response = await this.lookupDictionaryEntryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const LookupDictionaryEntryProviderEnum = {
} as const;
export type LookupDictionaryEntryProviderEnum = typeof LookupDictionaryEntryProviderEnum[keyof typeof LookupDictionaryEntryProviderEnum];
