/* tslint:disable */
/* eslint-disable */
/**
 * BeyondTranslate API
 * HTTP API for translation and dictionary lookups.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HealthResponseEnvelope,
    HealthResponseEnvelopeFromJSON,
    HealthResponseEnvelopeToJSON,
} from '../models/HealthResponseEnvelope';

/**
 * 
 */
export class SystemApi extends runtime.BaseAPI {

    /**
     * Creates request options for getHealth without sending the request
     */
    async getHealthRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Health check
     */
    async getHealthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthResponseEnvelope>> {
        const requestOptions = await this.getHealthRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthResponseEnvelopeFromJSON(jsonValue));
    }

    /**
     * Health check
     */
    async getHealth(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthResponseEnvelope> {
        const response = await this.getHealthRaw(initOverrides);
        return await response.value();
    }

}
