/* tslint:disable */
/* eslint-disable */
/**
 * BeyondTranslate API
 * HTTP API for translation and dictionary lookups.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type DetectLanguageRequest,
    DetectLanguageRequestFromJSON,
    DetectLanguageRequestToJSON,
} from '../models/DetectLanguageRequest';
import {
    type DetectLanguageResponseEnvelope,
    DetectLanguageResponseEnvelopeFromJSON,
    DetectLanguageResponseEnvelopeToJSON,
} from '../models/DetectLanguageResponseEnvelope';
import {
    type ErrorResponseEnvelope,
    ErrorResponseEnvelopeFromJSON,
    ErrorResponseEnvelopeToJSON,
} from '../models/ErrorResponseEnvelope';
import {
    type LanguagePairListEnvelope,
    LanguagePairListEnvelopeFromJSON,
    LanguagePairListEnvelopeToJSON,
} from '../models/LanguagePairListEnvelope';
import {
    type TranslateRequest,
    TranslateRequestFromJSON,
    TranslateRequestToJSON,
} from '../models/TranslateRequest';
import {
    type TranslateResponseEnvelope,
    TranslateResponseEnvelopeFromJSON,
    TranslateResponseEnvelopeToJSON,
} from '../models/TranslateResponseEnvelope';

export interface DetectLanguageOperationRequest {
    provider: DetectLanguageOperationProviderEnum;
    detectLanguageRequest: DetectLanguageRequest;
}

export interface GetSupportedLanguagePairsRequest {
    provider: GetSupportedLanguagePairsProviderEnum;
}

export interface TranslateTextRequest {
    provider: TranslateTextProviderEnum;
    translateRequest: TranslateRequest;
}

/**
 * 
 */
export class TranslationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for detectLanguage without sending the request
     */
    async detectLanguageRequestOpts(requestParameters: DetectLanguageOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['provider'] == null) {
            throw new runtime.RequiredError(
                'provider',
                'Required parameter "provider" was null or undefined when calling detectLanguage().'
            );
        }

        if (requestParameters['detectLanguageRequest'] == null) {
            throw new runtime.RequiredError(
                'detectLanguageRequest',
                'Required parameter "detectLanguageRequest" was null or undefined when calling detectLanguage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/translations/{provider}/detect-language`;
        urlPath = urlPath.replace('{provider}', encodeURIComponent(String(requestParameters['provider'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DetectLanguageRequestToJSON(requestParameters['detectLanguageRequest']),
        };
    }

    /**
     * Detect the language of input texts
     */
    async detectLanguageRaw(requestParameters: DetectLanguageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetectLanguageResponseEnvelope>> {
        const requestOptions = await this.detectLanguageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DetectLanguageResponseEnvelopeFromJSON(jsonValue));
    }

    /**
     * Detect the language of input texts
     */
    async detectLanguage(requestParameters: DetectLanguageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetectLanguageResponseEnvelope> {
        const response = await this.detectLanguageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSupportedLanguagePairs without sending the request
     */
    async getSupportedLanguagePairsRequestOpts(requestParameters: GetSupportedLanguagePairsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['provider'] == null) {
            throw new runtime.RequiredError(
                'provider',
                'Required parameter "provider" was null or undefined when calling getSupportedLanguagePairs().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/translations/{provider}/supported-language-pairs`;
        urlPath = urlPath.replace('{provider}', encodeURIComponent(String(requestParameters['provider'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List supported translation language pairs
     */
    async getSupportedLanguagePairsRaw(requestParameters: GetSupportedLanguagePairsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LanguagePairListEnvelope>> {
        const requestOptions = await this.getSupportedLanguagePairsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LanguagePairListEnvelopeFromJSON(jsonValue));
    }

    /**
     * List supported translation language pairs
     */
    async getSupportedLanguagePairs(requestParameters: GetSupportedLanguagePairsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LanguagePairListEnvelope> {
        const response = await this.getSupportedLanguagePairsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for translateText without sending the request
     */
    async translateTextRequestOpts(requestParameters: TranslateTextRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['provider'] == null) {
            throw new runtime.RequiredError(
                'provider',
                'Required parameter "provider" was null or undefined when calling translateText().'
            );
        }

        if (requestParameters['translateRequest'] == null) {
            throw new runtime.RequiredError(
                'translateRequest',
                'Required parameter "translateRequest" was null or undefined when calling translateText().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/translations/{provider}/translate`;
        urlPath = urlPath.replace('{provider}', encodeURIComponent(String(requestParameters['provider'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TranslateRequestToJSON(requestParameters['translateRequest']),
        };
    }

    /**
     * Translate text
     */
    async translateTextRaw(requestParameters: TranslateTextRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TranslateResponseEnvelope>> {
        const requestOptions = await this.translateTextRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TranslateResponseEnvelopeFromJSON(jsonValue));
    }

    /**
     * Translate text
     */
    async translateText(requestParameters: TranslateTextRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TranslateResponseEnvelope> {
        const response = await this.translateTextRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const DetectLanguageOperationProviderEnum = {
} as const;
export type DetectLanguageOperationProviderEnum = typeof DetectLanguageOperationProviderEnum[keyof typeof DetectLanguageOperationProviderEnum];
/**
 * @export
 */
export const GetSupportedLanguagePairsProviderEnum = {
} as const;
export type GetSupportedLanguagePairsProviderEnum = typeof GetSupportedLanguagePairsProviderEnum[keyof typeof GetSupportedLanguagePairsProviderEnum];
/**
 * @export
 */
export const TranslateTextProviderEnum = {
} as const;
export type TranslateTextProviderEnum = typeof TranslateTextProviderEnum[keyof typeof TranslateTextProviderEnum];
