mod detect_language_request;
mod detect_language_response;
mod language_pair;
mod look_up_request;
mod look_up_response;
mod text_detection;
mod text_translation;
mod translate_request;
mod translate_response;
mod word_definition;
mod word_image;
mod word_phrase;
mod word_pronunciation;
mod word_sentence;
mod word_tag;
mod word_tense;

pub use detect_language_request::DetectLanguageRequest;
pub use detect_language_response::DetectLanguageResponse;
pub use language_pair::LanguagePair;
pub use look_up_request::LookUpRequest;
pub use look_up_response::LookUpResponse;
pub use text_detection::TextDetection;
pub use text_translation::TextTranslation;
pub use translate_request::TranslateRequest;
pub use translate_response::TranslateResponse;
pub use word_definition::WordDefinition;
pub use word_image::WordImage;
pub use word_phrase::WordPhrase;
pub use word_pronunciation::WordPronunciation;
pub use word_sentence::WordSentence;
pub use word_tag::WordTag;
pub use word_tense::WordTense;
