// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

class RustSettingsDto {
  final String windowTheme;
  final String windowLanguage;
  final String rawJson;

  const RustSettingsDto({
    required this.windowTheme,
    required this.windowLanguage,
    required this.rawJson,
  });

  @override
  int get hashCode =>
      windowTheme.hashCode ^ windowLanguage.hashCode ^ rawJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustSettingsDto &&
          runtimeType == other.runtimeType &&
          windowTheme == other.windowTheme &&
          windowLanguage == other.windowLanguage &&
          rawJson == other.rawJson;
}
