// This file is automatically generated. Do not edit by hand.
// Generated by `python3 scripts/codegen.py`.

import Foundation

struct AppearanceSettingsPatch: Codable {
  var language: String?
  var themeMode: String?
}
