// This file is automatically generated. Do not edit by hand.

import Foundation

extension DeepLProviderConfig {
  static let configFields: [ProviderConfigField] = [
    ProviderConfigField(
      key: "appKey", label: "API Key", placeholder: "", isSecret: true, isOptional: false),
    ProviderConfigField(
      key: "baseUrl", label: "Base URL", placeholder: "https://api.deepl.com", isSecret: false,
      isOptional: true),
  ]
}
