// This file is automatically generated. Do not edit by hand.

import Foundation

struct DeepLProviderConfig: Codable {
  var apiKey: String
  var baseUrl: String?

  enum CodingKeys: String, CodingKey {
    case apiKey = "appKey"
    case baseUrl
  }
}
