// This file is automatically generated. Do not edit by hand.
// Generated by `python3 scripts/codegen.py`.

import Foundation

struct GeneralSettings: Codable {
  var launchAtLogin: Bool
  var showMenuBar: Bool
  var defaultOcrService: String
  var autoCopyDetectedText: Bool
  var defaultDirectoryService: String
  var defaultTranslationService: String
  var translationMode: TranslationMode
  var translationTargets: [TranslationTarget]
  var inputSubmitMode: InputSubmitMode
  var doubleClickCopyResult: Bool
}
