// This file is automatically generated. Do not edit by hand.
// Generated by `python3 scripts/codegen.py`.

import Foundation

struct GoogleProviderConfig: Codable {
  var apiKey: String
  var baseUrl: String?

  enum CodingKeys: String, CodingKey {
    case apiKey = "appKey"
    case baseUrl
  }
}
