// This file is automatically generated. Do not edit by hand.
// Generated by `python3 scripts/codegen.py`.

import Foundation

extension GoogleProviderConfig {
  static let configFields: [ProviderConfigField] = [
    ProviderConfigField(
      key: "appKey", label: "API Key", placeholder: "AIza…", isSecret: true, isOptional: false),
    ProviderConfigField(
      key: "baseUrl", label: "Base URL", placeholder: "https://translation.googleapis.com",
      isSecret: false, isOptional: true),
  ]
}
