// This file is automatically generated. Do not edit by hand.

import Foundation

extension IcibaProviderConfig {
  static let configFields: [ProviderConfigField] = [
    ProviderConfigField(
      key: "appKey", label: "API Key", placeholder: "", isSecret: true, isOptional: false),
    ProviderConfigField(
      key: "baseUrl", label: "Base URL", placeholder: "", isSecret: false, isOptional: true),
  ]
}
