// This file is automatically generated. Do not edit by hand.

import Foundation

enum InputSubmitMode: String, Codable, CaseIterable, Identifiable {
  case enter
  case commandEnter

  var id: String { rawValue }
}
