// This file is automatically generated. Do not edit by hand.
// Generated by `python3 scripts/codegen.py`.

import Foundation

enum InputSubmitMode: String, Codable, CaseIterable, Identifiable {
  case enter
  case commandEnter

  var id: String { rawValue }
}
