// This file is automatically generated. Do not edit by hand.

import Foundation

enum ProviderCapability: String, Codable, CaseIterable, Identifiable {
  case dictionary
  case translation

  var id: String { rawValue }
}
