// This file is automatically generated. Do not edit by hand.
// Generated by `python3 scripts/codegen.py`.

import Foundation

enum ProviderType: String, Codable, CaseIterable, Identifiable {
  case baidu
  case caiyun
  case deepL = "deepl"
  case google
  case iciba
  case tencent
  case youdao

  var id: String { rawValue }
}
