// This file is automatically generated. Do not edit by hand.

import Foundation

struct ProviderConfigField: Identifiable {
  var id: String { key }
  let key: String
  let label: String
  let placeholder: String
  let isSecret: Bool
  let isOptional: Bool
}
