// This file is automatically generated. Do not edit by hand.
// Generated by `python3 scripts/codegen.py`.

import Foundation

enum ProviderCapability: String, Codable, CaseIterable, Identifiable {
  case translation
  case dictionary

  var id: String { rawValue }
}
