// This file is automatically generated. Do not edit by hand.
// Generated by `python3 scripts/codegen.py`.

import Foundation

struct ProviderConfigEntry: Codable {
  var id: String
  var type: String
  var fields: [String: String]
  var capabilities: [String]
}
