// This file is automatically generated. Do not edit by hand.

import Foundation

struct Settings: Codable {
  var lastUpdated: UInt64
  var providers: [String: ProviderConfigEntry]
  var general: GeneralSettings
  var shortcuts: ShortcutSettings
  var appearance: AppearanceSettings
  var advanced: AdvancedSettings
}
