// This file is automatically generated. Do not edit by hand.
// Generated by `python3 scripts/codegen.py`.

import Foundation

struct Settings: Codable {
  var lastUpdated: UInt64
  var providers: [String: ProviderConfigEntry]
  var general: GeneralSettings
  var shortcuts: ShortcutSettings
  var appearance: AppearanceSettings
  var advanced: AdvancedSettings
}
