// This file is automatically generated. Do not edit by hand.
// Generated by `python3 scripts/generate_settings.py`.

import Foundation

struct Settings: Codable {
  var shortcuts: ShortcutSettings
  var appearance: AppearanceSettings
  var advanced: AdvancedSettings
}

struct ShortcutSettings: Codable {
  var toggleApp: String
}

struct ShortcutSettingsPatch: Codable {
  var toggleApp: String?
}

struct AppearanceSettings: Codable {
  var language: String
  var themeMode: String
}

struct AppearanceSettingsPatch: Codable {
  var language: String?
  var themeMode: String?
}

struct AdvancedSettings: Codable {
  var launchAtLogin: Bool
  var proxy: String
}

struct AdvancedSettingsPatch: Codable {
  var launchAtLogin: Bool?
  var proxy: String?
}
