// This file is automatically generated. Do not edit by hand.

import Foundation

struct ShortcutSettings: Codable {
  var toggleApp: String
  var hideApp: String
  var extractFromScreenSelection: String
  var extractFromScreenCapture: String
  var extractFromClipboard: String
}
