// This file is automatically generated. Do not edit by hand.

import Foundation

struct ShortcutSettingsPatch: Codable {
  var toggleApp: String? = nil
  var hideApp: String? = nil
  var extractFromScreenSelection: String? = nil
  var extractFromScreenCapture: String? = nil
  var extractFromClipboard: String? = nil
}
