// This file is automatically generated. Do not edit by hand.
// Generated by `python3 scripts/codegen.py`.

import Foundation

struct ShortcutSettingsPatch: Codable {
  var toggleApp: String?
  var hideApp: String?
  var extractFromScreenSelection: String?
  var extractFromScreenCapture: String?
  var extractFromClipboard: String?
}
