// This file is automatically generated. Do not edit by hand.

import Foundation

extension TencentProviderConfig {
  static let configFields: [ProviderConfigField] = [
    ProviderConfigField(
      key: "secretId", label: "Secret ID", placeholder: "", isSecret: false, isOptional: false),
    ProviderConfigField(
      key: "secretKey", label: "Secret Key", placeholder: "", isSecret: true, isOptional: false),
    ProviderConfigField(
      key: "baseUrl", label: "Base URL", placeholder: "", isSecret: false, isOptional: true),
  ]
}
