// This file is automatically generated. Do not edit by hand.

import Foundation

enum TranslationMode: String, Codable, CaseIterable, Identifiable {
  case auto
  case manual

  var id: String { rawValue }
}
