// This file is automatically generated. Do not edit by hand.
// Generated by `python3 scripts/codegen.py`.

import Foundation

enum TranslationMode: String, Codable, CaseIterable, Identifiable {
  case auto
  case manual

  var id: String { rawValue }
}
