// This file is automatically generated. Do not edit by hand.
// Generated by `python3 scripts/codegen.py`.

import Foundation

struct TranslationTarget: Codable, Identifiable {
  var source: String
  var target: String

  var id: String { "\(source)->\(target)" }
}
