// This file is automatically generated. Do not edit by hand.
// Generated by `python3 scripts/codegen.py`.

import Foundation

extension YoudaoProviderConfig {
  static let configFields: [ProviderConfigField] = [
    ProviderConfigField(
      key: "appKey", label: "App Key", placeholder: "", isSecret: true, isOptional: false),
    ProviderConfigField(
      key: "appSecret", label: "App Secret", placeholder: "", isSecret: true, isOptional: false),
    ProviderConfigField(
      key: "baseUrl", label: "Base URL", placeholder: "https://openapi.youdao.com", isSecret: false,
      isOptional: true),
    ProviderConfigField(
      key: "pictureBaseUrl", label: "Picture Base URL", placeholder: "https://picdict.youdao.com",
      isSecret: false, isOptional: true),
  ]
}
