// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

class LookUpRequest {
  final String sourceLanguage;
  final String targetLanguage;
  final String word;

  const LookUpRequest({
    required this.sourceLanguage,
    required this.targetLanguage,
    required this.word,
  });

  @override
  int get hashCode =>
      sourceLanguage.hashCode ^ targetLanguage.hashCode ^ word.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LookUpRequest &&
          runtimeType == other.runtimeType &&
          sourceLanguage == other.sourceLanguage &&
          targetLanguage == other.targetLanguage &&
          word == other.word;
}

class LookUpResponse {
  final List<TextTranslation> translations;
  final String? word;
  final String? tip;
  final List<WordTag>? tags;
  final List<WordDefinition>? definitions;
  final List<WordPronunciation>? pronunciations;
  final List<WordImage>? images;
  final List<WordPhrase>? phrases;
  final List<WordTense>? tenses;
  final List<WordSentence>? sentences;

  const LookUpResponse({
    required this.translations,
    this.word,
    this.tip,
    this.tags,
    this.definitions,
    this.pronunciations,
    this.images,
    this.phrases,
    this.tenses,
    this.sentences,
  });

  @override
  int get hashCode =>
      translations.hashCode ^
      word.hashCode ^
      tip.hashCode ^
      tags.hashCode ^
      definitions.hashCode ^
      pronunciations.hashCode ^
      images.hashCode ^
      phrases.hashCode ^
      tenses.hashCode ^
      sentences.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LookUpResponse &&
          runtimeType == other.runtimeType &&
          translations == other.translations &&
          word == other.word &&
          tip == other.tip &&
          tags == other.tags &&
          definitions == other.definitions &&
          pronunciations == other.pronunciations &&
          images == other.images &&
          phrases == other.phrases &&
          tenses == other.tenses &&
          sentences == other.sentences;
}

class TextTranslation {
  final String? detectedSourceLanguage;
  final String text;
  final String? audioUrl;

  const TextTranslation({
    this.detectedSourceLanguage,
    required this.text,
    this.audioUrl,
  });

  @override
  int get hashCode =>
      detectedSourceLanguage.hashCode ^ text.hashCode ^ audioUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextTranslation &&
          runtimeType == other.runtimeType &&
          detectedSourceLanguage == other.detectedSourceLanguage &&
          text == other.text &&
          audioUrl == other.audioUrl;
}

class TranslateRequest {
  final String? sourceLanguage;
  final String? targetLanguage;
  final String text;

  const TranslateRequest({
    this.sourceLanguage,
    this.targetLanguage,
    required this.text,
  });

  @override
  int get hashCode =>
      sourceLanguage.hashCode ^ targetLanguage.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranslateRequest &&
          runtimeType == other.runtimeType &&
          sourceLanguage == other.sourceLanguage &&
          targetLanguage == other.targetLanguage &&
          text == other.text;
}

class TranslateResponse {
  final List<TextTranslation> translations;

  const TranslateResponse({
    required this.translations,
  });

  @override
  int get hashCode => translations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranslateResponse &&
          runtimeType == other.runtimeType &&
          translations == other.translations;
}

class WordDefinition {
  final String? type;
  final String? name;
  final List<String>? values;

  const WordDefinition({
    this.type,
    this.name,
    this.values,
  });

  @override
  int get hashCode => type.hashCode ^ name.hashCode ^ values.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WordDefinition &&
          runtimeType == other.runtimeType &&
          type == other.type &&
          name == other.name &&
          values == other.values;
}

class WordImage {
  final String url;

  const WordImage({
    required this.url,
  });

  @override
  int get hashCode => url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WordImage &&
          runtimeType == other.runtimeType &&
          url == other.url;
}

class WordPhrase {
  final String text;
  final List<String> translations;

  const WordPhrase({
    required this.text,
    required this.translations,
  });

  @override
  int get hashCode => text.hashCode ^ translations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WordPhrase &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          translations == other.translations;
}

class WordPronunciation {
  final String? type;
  final String? phoneticSymbol;
  final String? audioUrl;

  const WordPronunciation({
    this.type,
    this.phoneticSymbol,
    this.audioUrl,
  });

  @override
  int get hashCode =>
      type.hashCode ^ phoneticSymbol.hashCode ^ audioUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WordPronunciation &&
          runtimeType == other.runtimeType &&
          type == other.type &&
          phoneticSymbol == other.phoneticSymbol &&
          audioUrl == other.audioUrl;
}

class WordSentence {
  final String text;
  final List<String> translations;

  const WordSentence({
    required this.text,
    required this.translations,
  });

  @override
  int get hashCode => text.hashCode ^ translations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WordSentence &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          translations == other.translations;
}

class WordTag {
  final String name;

  const WordTag({
    required this.name,
  });

  @override
  int get hashCode => name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WordTag &&
          runtimeType == other.runtimeType &&
          name == other.name;
}

class WordTense {
  final String? type;
  final String? name;
  final List<String>? values;

  const WordTense({
    this.type,
    this.name,
    this.values,
  });

  @override
  int get hashCode => type.hashCode ^ name.hashCode ^ values.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WordTense &&
          runtimeType == other.runtimeType &&
          type == other.type &&
          name == other.name &&
          values == other.values;
}
