// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../domain/settings.dart';
import '../frb_generated.dart';
import 'mirrors.dart';

// These functions are ignored because they are not marked as `pub`: `new`, `optional_trimmed`, `provider_entry`, `run_on_worker_thread`, `update_with_result`, `update`, `validate_optional_required`, `validate_provider_id`, `validate_required`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RuntimeInner`, `RuntimeState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Runtime>>
abstract class Runtime implements RustOpaqueInterface {
  RuntimeDictionary dictionary({required String providerId});

  factory Runtime({required String storageDir}) =>
      RustLib.instance.api.crateApiRuntimeRuntimeNew(storageDir: storageDir);

  RuntimeSettings settings();

  RuntimeTranslation translation({required String providerId});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RuntimeDictionary>>
abstract class RuntimeDictionary implements RustOpaqueInterface {
  Future<LookUpResponse> lookup({required LookUpRequest request});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RuntimeSettings>>
abstract class RuntimeSettings implements RustOpaqueInterface {
  Future<RustProviderEntry?> deleteProvider({required String providerId});

  Future<RustSettingsDto> get_();

  Future<String> getJson();

  Future<RustProviderEntry?> getProvider({required String providerId});

  Future<List<RustProviderEntry>> listProviders();

  Future<RustSettingsDto> setWindowLanguage({required String language});

  Future<RustSettingsDto> setWindowTheme({required String theme});

  Future<RustProviderEntry> updateProvider(
      {required String providerId, required String configYaml});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RuntimeTranslation>>
abstract class RuntimeTranslation implements RustOpaqueInterface {
  Future<TranslateResponse> translate({required TranslateRequest request});
}

class RustProviderEntry {
  final String id;
  final String type;
  final String configYaml;

  const RustProviderEntry({
    required this.id,
    required this.type,
    required this.configYaml,
  });

  @override
  int get hashCode => id.hashCode ^ type.hashCode ^ configYaml.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustProviderEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          type == other.type &&
          configYaml == other.configYaml;
}
