// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../domain/settings.dart';
import '../frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`, `optional_trimmed`, `run_on_worker_thread`, `update`, `validate_provider_type`, `validate_required`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RuntimeInner`, `RuntimeState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Runtime>>
abstract class Runtime implements RustOpaqueInterface {
  RuntimeDictionary dictionary({required String providerType});

  factory Runtime({required String storageDir}) =>
      RustLib.instance.api.crateApiRuntimeRuntimeNew(storageDir: storageDir);

  RuntimeSettings settings();

  RuntimeTranslation translation({required String providerType});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RuntimeDictionary>>
abstract class RuntimeDictionary implements RustOpaqueInterface {
  Future<RustLookupResponse> lookup({required RustLookupRequest request});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RuntimeSettings>>
abstract class RuntimeSettings implements RustOpaqueInterface {
  Future<RustSettingsDto> get_();

  Future<String> getJson();

  Future<RustSettingsDto> setWindowLanguage({required String language});

  Future<RustSettingsDto> setWindowTheme({required String theme});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RuntimeTranslation>>
abstract class RuntimeTranslation implements RustOpaqueInterface {
  Future<RustTranslateResponse> translate(
      {required RustTranslateRequest request});
}

class RustLookupRequest {
  final String? providerConfigYaml;
  final String sourceLanguage;
  final String targetLanguage;
  final String word;

  const RustLookupRequest({
    this.providerConfigYaml,
    required this.sourceLanguage,
    required this.targetLanguage,
    required this.word,
  });

  @override
  int get hashCode =>
      providerConfigYaml.hashCode ^
      sourceLanguage.hashCode ^
      targetLanguage.hashCode ^
      word.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustLookupRequest &&
          runtimeType == other.runtimeType &&
          providerConfigYaml == other.providerConfigYaml &&
          sourceLanguage == other.sourceLanguage &&
          targetLanguage == other.targetLanguage &&
          word == other.word;
}

class RustLookupResponse {
  final String providerType;
  final String? word;
  final List<String> definitions;
  final List<String> pronunciations;
  final List<String> tenses;

  const RustLookupResponse({
    required this.providerType,
    this.word,
    required this.definitions,
    required this.pronunciations,
    required this.tenses,
  });

  @override
  int get hashCode =>
      providerType.hashCode ^
      word.hashCode ^
      definitions.hashCode ^
      pronunciations.hashCode ^
      tenses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustLookupResponse &&
          runtimeType == other.runtimeType &&
          providerType == other.providerType &&
          word == other.word &&
          definitions == other.definitions &&
          pronunciations == other.pronunciations &&
          tenses == other.tenses;
}

class RustTranslateRequest {
  final String? providerConfigYaml;
  final String? sourceLanguage;
  final String targetLanguage;
  final String text;

  const RustTranslateRequest({
    this.providerConfigYaml,
    this.sourceLanguage,
    required this.targetLanguage,
    required this.text,
  });

  @override
  int get hashCode =>
      providerConfigYaml.hashCode ^
      sourceLanguage.hashCode ^
      targetLanguage.hashCode ^
      text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustTranslateRequest &&
          runtimeType == other.runtimeType &&
          providerConfigYaml == other.providerConfigYaml &&
          sourceLanguage == other.sourceLanguage &&
          targetLanguage == other.targetLanguage &&
          text == other.text;
}

class RustTranslateResponse {
  final String providerType;
  final List<String> translations;
  final String? detectedSourceLanguage;

  const RustTranslateResponse({
    required this.providerType,
    required this.translations,
    this.detectedSourceLanguage,
  });

  @override
  int get hashCode =>
      providerType.hashCode ^
      translations.hashCode ^
      detectedSourceLanguage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustTranslateResponse &&
          runtimeType == other.runtimeType &&
          providerType == other.providerType &&
          translations == other.translations &&
          detectedSourceLanguage == other.detectedSourceLanguage;
}
