// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `load_runtime_registry`, `lookup_with_runtime_impl`, `parse_provider_config`, `run_on_worker_thread`, `translate_with_runtime_impl`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

Future<RustTranslateDebugResponse> translateWithRuntime(
        {required RustTranslateDebugRequest request}) =>
    RustLib.instance.api.crateApiSimpleTranslateWithRuntime(request: request);

Future<RustLookupDebugResponse> lookupWithRuntime(
        {required RustLookupDebugRequest request}) =>
    RustLib.instance.api.crateApiSimpleLookupWithRuntime(request: request);

class RustLookupDebugRequest {
  final String providerType;
  final String providerConfigYaml;
  final String sourceLanguage;
  final String targetLanguage;
  final String word;

  const RustLookupDebugRequest({
    required this.providerType,
    required this.providerConfigYaml,
    required this.sourceLanguage,
    required this.targetLanguage,
    required this.word,
  });

  @override
  int get hashCode =>
      providerType.hashCode ^
      providerConfigYaml.hashCode ^
      sourceLanguage.hashCode ^
      targetLanguage.hashCode ^
      word.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustLookupDebugRequest &&
          runtimeType == other.runtimeType &&
          providerType == other.providerType &&
          providerConfigYaml == other.providerConfigYaml &&
          sourceLanguage == other.sourceLanguage &&
          targetLanguage == other.targetLanguage &&
          word == other.word;
}

class RustLookupDebugResponse {
  final String providerType;
  final String? word;
  final List<String> definitions;
  final List<String> pronunciations;
  final List<String> tenses;

  const RustLookupDebugResponse({
    required this.providerType,
    this.word,
    required this.definitions,
    required this.pronunciations,
    required this.tenses,
  });

  @override
  int get hashCode =>
      providerType.hashCode ^
      word.hashCode ^
      definitions.hashCode ^
      pronunciations.hashCode ^
      tenses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustLookupDebugResponse &&
          runtimeType == other.runtimeType &&
          providerType == other.providerType &&
          word == other.word &&
          definitions == other.definitions &&
          pronunciations == other.pronunciations &&
          tenses == other.tenses;
}

class RustTranslateDebugRequest {
  final String providerType;
  final String providerConfigYaml;
  final String? sourceLanguage;
  final String targetLanguage;
  final String text;

  const RustTranslateDebugRequest({
    required this.providerType,
    required this.providerConfigYaml,
    this.sourceLanguage,
    required this.targetLanguage,
    required this.text,
  });

  @override
  int get hashCode =>
      providerType.hashCode ^
      providerConfigYaml.hashCode ^
      sourceLanguage.hashCode ^
      targetLanguage.hashCode ^
      text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustTranslateDebugRequest &&
          runtimeType == other.runtimeType &&
          providerType == other.providerType &&
          providerConfigYaml == other.providerConfigYaml &&
          sourceLanguage == other.sourceLanguage &&
          targetLanguage == other.targetLanguage &&
          text == other.text;
}

class RustTranslateDebugResponse {
  final String providerType;
  final List<String> translations;
  final String? detectedSourceLanguage;

  const RustTranslateDebugResponse({
    required this.providerType,
    required this.translations,
    this.detectedSourceLanguage,
  });

  @override
  int get hashCode =>
      providerType.hashCode ^
      translations.hashCode ^
      detectedSourceLanguage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustTranslateDebugResponse &&
          runtimeType == other.runtimeType &&
          providerType == other.providerType &&
          translations == other.translations &&
          detectedSourceLanguage == other.detectedSourceLanguage;
}
